### ISSUE TITLE
IllegalStateException in SyncProject

### ISSUE THREAD

**Issue by filfreire** [zerocracy/farm#2119] opened 2019-07-19 08:46 UTC
@g4s8 caught the following error in a merged Pull request in this repo https://github.com/yegor256/tacit/pull/202

```
PID: 4@9a947b19-47b2-43b3-a098-15eb9dcbb263, thread: pool-5-thread-6
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "wbs.xml" in "C7BNDNSNR" in 2min: java.util.concurrent.locks.ReentrantLock@2b9d2c54[Locked by thread pool-5-thread-1]
0.48.2: CID: 22220f4c-515d-44fe-9418-675266b62ce6, Type: "Close job"
```

Link where it was seen happening: https://github.com/yegor256/tacit/pull/202#issuecomment-513144245

**Comment by 0crat** [comment] 2019-07-19 08:46
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-07-19 08:48
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9a947b19-47b2-43b3-a098-15eb9dcbb263, thread: pool-319-thread-1
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "catalog.xml" in "PMO" in 2min: java.util.concurrent.locks.ReentrantLock@16c55f0b[Locked by thread BkParallel-1]
```

[0.48.2](https://github.com/zerocracy/farm): Issue: zerocracy/farm#2119, Action: `opened`

**Comment by victornoel** [comment] 2019-07-21 08:28
@g4s8 same is happening in multiple projects where I participate, there is some kind of deadlock somewhere, this is critical I believe because 0crat work is stopped and people aren't paid!
- https://github.com/llorllale/cactoos-matchers/pull/131#issuecomment-513514699
- https://github.com/yegor256/cactoos-http/pull/92#issuecomment-513514704
- https://github.com/yegor256/cactoos/pull/1158#issuecomment-513514708
- https://github.com/yegor256/cactoos/issues/1119#issuecomment-513514716
- https://github.com/llorllale/cactoos-matchers/pull/134#issuecomment-513517278
- https://github.com/llorllale/cactoos-matchers/issues/129#issuecomment-513517282

**Comment by g4s8** [comment] 2019-07-21 09:08
@victornoel this is the list of current issues with synchronization:
 - it's working on project basis, when someone locks project file, no one else can access any other file in the project, it's implemented because of hidden and unobvious files modifications with auto-transofrmations (see `Rd*` files especially `RdAuto`). PMO project can be accessed very frequently (0crat read multiple files from this project on each page request, one each Github webhook and on each chat message). So when 0crat is loaded by many requests simultaneously, it's starting to fail to process some requests because of locking timeout. File access itself is not slow operation, since 0crat and S3 bucket with files are located in same AWS region and 0crat may read/write with speed up to 1GB/s.
 - We have a mechanism to kill hanging locks after timeout, it's `Terminator` classes, I don't really like the design of these classes, because it's hard to understand. Also, it has can be broken for unknown reason - sometimes it's stop working, I tried to reproduce it locally many times but without success, all I know about it, is that it usually stops working on highload, when many requests are waiting for lock. With combination of first issue, we're getting this #2119 bug.

**Comment by g4s8** [comment] 2019-07-21 09:08
@0crat assign @victornoel

**Comment by 0crat** [comment] 2019-07-21 09:10
> @0crat assign @victornoel  ([here](https://github.com/zerocracy/farm/issues/2119#issuecomment-513537081))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2119](https://github.com/zerocracy/farm/issues/2119), see [§21](http://www.zerocracy.com/policy.html#21); @victornoel[/z](https://www.0crat.com/u/victornoel) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment] 2019-07-21 09:16
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment] 2019-07-21 09:17
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @filfreire[/z](https://www.0crat.com/u/filfreire)

**Comment by victornoel** [comment] 2019-07-21 10:35
@g4s8 Here are some feedbacks on the matter

Random questions/hypothesis while reading:
- Both `SyncFarm` and `ExtFarm` decorates the `find` method with `Guts`, is that expected?
- I understand the locking is done via the database, I'm sure there is a good reason for this, but why not use in process locks?
- If I understand well, the `Project` abstraction was made so that locking happens on a per-file basis, but in practice, the `PgLocks` implementation on which `SyncProject` does not care about the file and just keep one lock per project. Is that correct?

Some ideas to improve things in the short term:
- have the `Map` inside `Terminator` track `Project` by their `pid` instead of their `Object` because we are never sure that all the `Project` classes properly implements `equals`/`hashCode`. (by the way this is related to our discussion on telegram about envelopes and `equals`, maps are not meant to hold behavioural objects but data that is clearly hashable). This could solve some inconsistency problems maybe...
- Again, in `Terminator`, rely on the `ConcurrentMap` abstraction to insert elements in it instead of using `synchronized`, it should improve performance and maybe even correctness.
- do some stress testing of `Terminator` to validate its actually doing its job.
- `PgLock` is hell to understand, I think this should be investigated a bit more and maybe try to simplify it even at the cost of performance (anyway performance are already bad) to get more correctness. There could be some improvements to be done to the whole implementation in the short term that would improve performance or correct bugs. Maybe with stress testing of the implementation and validating that it does not deadlock or stuffs like that.

In the medium term:
- consider differentiating read only operation from write operations, it is not without reasons that `ReadWriteLock` have a specific behaviour related to that. This would prevent all the web access from blocking stuffs too much. You could even prioritize write operation then.

In the longer term:
- you don't really want a lock, you want a queue: there are tasks to do but they can be done only one by one per project. So you need one queue per project. It is possible to implement queues in the database (to answer the same requirements that motivated implementing the lock in the database) and it will be much more efficient and easy to understand. I can find some resources on that.
- I would even ask (but this is a huge endeavour, I would say a rewrite): isn't it the time to move to real even-oriented architecture that handles all this complexity for you instead of (badly, because we aren't experts) reinventing the wheel?

**Comment by g4s8** [comment] 2019-07-21 11:15
@victornoel just to clarify a bit: right now we have locks implementation based on `ReentrantLock`, but we're going to use database locks (it's disabled now) to be able to start multiple instances of farm simultaneously (farm cluster).

**Comment by victornoel** [comment] 2019-07-21 11:32
@g4s8 ah ok, I missed the fact that `PgLocks` wasn't used but `TestLocks` was.

In that cas, I think my short term recommendations still applies, but I would add one more:
- use fair `ReentrantLock`s in order to avoid threads starving, I don't think the perfomance impact is going to be a problem at all.

**Comment by victornoel** [comment] 2019-07-21 11:48
@g4s8 if you boost this job, I can do a PR with the less risk-taking evolutions that I proposed

**Comment by victornoel** [comment] 2019-07-21 11:56
@g4s8 another recommendation in the short term:
- add a `finalize` (or another mean to detect GC) method to `WarnItem` so that it complains if the item wasn't closed as expected when the object is GCed. This could help diagnose future problems.

**Comment by victornoel** [comment] 2019-07-21 11:59
> @g4s8 another recommendation in the short term:
> 
>     * add a `finalize` (or another mean to detect GC) method to `WarnItem` so that it complains if the item wasn't closed as expected when the object is GCed. This could help diagnose future problems.

This would help detect for example that `Txn` is not calling close :)

**Comment by victornoel** [comment] 2019-07-21 12:57
@g4s8 about using pg as the lock implementation, a better solution would be to use PostgreSQL advisory locks instead of a table and implement things by hand. See http://shiroyasha.io/advisory-locks-and-how-to-use-them.html for example. The example given on this page is very similar to what is done in farm.

**Comment by victornoel** [comment] 2019-07-21 15:13
@0crat status

**Comment by 0crat** [comment] 2019-07-21 15:14
> @0crat status ([here](https://github.com/zerocracy/farm/issues/2119#issuecomment-513562748))

@victornoel This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#2119](https://github.com/zerocracy/farm/issues/2119) is [in scope](http://www.zerocracy.com/policy.html#14) for 6hr
  * The role is `DEV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [6hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @filfreire[/z](https://www.0crat.com/u/filfreire): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%232119%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment] 2019-07-21 15:52
@filfreire for the record, if the bot has not re-processed the close event, you can ask ARC to do so with `@0crat out`

**Comment by 0crat** [comment] 2019-07-21 15:52
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/2119#issuecomment-513565748); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by victornoel** [comment] 2019-09-11 17:14
@g4s8 I have created the following issues, I think my job is done here and we should close this ticket
- #2143
- #2144
- #2145
- #2146
- #2148
- #2149
- #2150

**Comment by victornoel** [comment] 2019-09-22 10:17
@filfreire can you close this issue?

**Comment by victornoel** [comment] 2019-09-24 18:02
@g4s8 can you close this? it seems @filfreire is not with us anymore

**Comment by g4s8** [comment] 2019-09-24 19:13
@victornoel sure, thanks

**Closed by g4s8** 2019-09-24 19:13 UTC
Labels: scope

**Comment by 0crat** [comment] 2019-09-24 19:34
Job [#2119](https://github.com/zerocracy/farm/issues/2119) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't retrieve data and time of add

**Comment by 0crat** [comment] 2019-09-24 19:36
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2019-09-24 19:36
Job [#2119](https://github.com/zerocracy/farm/issues/2119) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by 0crat** [comment] 2019-09-24 19:39
The job [#2119](https://github.com/zerocracy/farm/issues/2119) is now out of scope

**Comment by paulodamaso** [comment] 2019-09-24 20:15
@0crat quality good

**Comment by 0crat** [comment] 2019-09-24 20:32
> @0crat quality good ([here](https://github.com/zerocracy/farm/issues/2119#issuecomment-534729305))

@paulodamaso The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment] 2019-09-24 20:33
Quality review completed: +4 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment] 2019-09-24 20:35
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)
