### ISSUE TITLE
add_speed_bonus test is commented out

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1654] opened 2018-08-25 13:29 UTC
add_speed_bonus stakeholder test is commented out, but there is no todo to fix/uncomment it.
So there is a possibility that the speed bonus breaks in the future and we won't know about it.

**Comment by 0crat** [comment] 2018-08-25 13:29
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment] 2018-08-26 11:38
@krzyk it's a duplicate of #1535

**Comment by 0crat** [comment] 2018-08-26 11:39
Job `gh:zerocracy/farm#1654` is not assigned, can't get performer

**Closed by g4s8** 2018-08-26 11:38 UTC
Labels: duplicate
