### ISSUE TITLE
Error when inviting a user

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1921] opened 2019-03-03 13:51 UTC
I tried to invite a user whose resume was assigned to me, I got the following error (in telegram):
```
PID: 4@76e332c2-1115-49c5-bda0-6eb81587d423, thread: pool-19-thread-71
org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl[252] java.lang.ClassCastException: javax.json.JsonValueImpl cannot be cast to javax.json.JsonString


0.43.2 (https://github.com/zerocracy/farm): CID: ca31b83c-dd70-4cf2-b067-fa32da3375b7 (https://www.0crat.com/footprint/PMO/ca31b83c-dd70-4cf2-b067-fa32da3375b7), Type: "Invite a friend"
```

**Comment by 0crat** [comment] 2019-03-03 13:51
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment] 2019-03-03 14:56
@g4s8 also I didn't get the 32 points associated with reviewing a resume

**Comment by g4s8** [comment] 2019-03-03 15:50
@victornoel thank for reporting, but it's a duplicate of #1753

**Closed by g4s8** 2019-03-03 15:50 UTC
Labels: duplicate

**Comment by 0crat** [comment] 2019-03-03 15:57
Job `gh:zerocracy/farm#1921` is not assigned, can't get performer
