### ISSUE TITLE
cannot apply to sandbox project because of acquiring "people.xml" in "PMO"

### ISSUE THREAD

**Issue by cancellier** [zerocracy/farm#1023] opened 2018-05-16 20:46 UTC
An `java.lang.IllegalStateException` was thrown when I have tried to apply in sandbox project.
I have sent `apply sandbox` to `0crat` on Telegram and it replied :
> PID: 4@8bd6a11d-7e2f-4d32-8715-2013ba17efe3, thread: zerocrat_bot Telegram Executor
> com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 70a3978a8bed/20ms/0/5/true/false by BkParallel-1
> 
> 1.0-SNAPSHOT (https://github.com/zerocracy/farm): ID: 344195402, From: cancellier, ChatId: 575490747

**Comment by 0crat** [comment] 2018-05-16 20:46
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-05-16 20:46
@cancellier[/z](https://www.0crat.com/u/cancellier) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment] 2018-05-19 14:17
The job [#1023](https://github.com/zerocracy/farm/issues/1023) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1391416381); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment] 2018-05-19 14:17
Job `gh:zerocracy/farm#1023` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment] 2018-05-19 14:17
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @cancellier[/z](https://www.0crat.com/u/cancellier)

**Comment by 0crat** [comment] 2018-05-19 14:17
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment] 2018-05-19 14:18
@cancellier have you tried to apply again? Did it work?

**Comment by wholegroup** [comment] 2018-06-20 12:28
@yegor256 It looks like I have the same issue:

I get an exception when I say hello 

>PID: 4@913782de-5eeb-4cf1-9e4d-4c5e85dde386, thread: zerocrat_bot Telegram Executor
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: d2e6b100d1f8/35min/0/3/true/false by AsyncFlush-3

**Comment by wholegroup** [comment] 2018-06-20 12:33
@yegor256 and the same exception in slack

>PID: 4@913782de-5eeb-4cf1-9e4d-4c5e85dde386, thread: Grizzly(2)
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: d2e6b100d1f8/43min/0/1/true/false by AsyncFlush-3
>
>[0.22.8](https://github.com/zerocracy/farm): Channel: DBAKK44H1, Sender: U0Q1V21HA, EventType: SLACK_MESSAGE_POSTED

**Comment by yegor256** [comment] 2018-06-24 07:47
@g4s8 what do you think?

**Comment by g4s8** [comment] 2018-06-24 10:51
@yegor256 I think it was fixed with #1168 issue. @wholegroup can you retry now? @cancellier does it work for you now?

**Comment by cancellier** [comment] 2018-06-24 11:05
It works now, the error message written after my incorrect request ("apply sandbox") is now right.
I did a request to apply to a sandbox project with a correct request and I will wait for ;-)
Thanks guys.

**Comment by wholegroup** [comment] 2018-06-24 18:28
@g4s8 now it works well. thanks!

**Comment by g4s8** [comment] 2018-06-24 18:32
@yegor256 it's not reproducing now

**Closed by g4s8** 2018-06-24 18:32 UTC
Labels: scope

**Comment by 0crat** [comment] 2018-06-24 18:51
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment] 2018-06-24 18:51
The job [#1023](https://github.com/zerocracy/farm/issues/1023) is now out of scope
