### ISSUE TITLE
ZLD payments for issues not sent

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1833] opened 2018-12-21 08:35 UTC
My wallet is set to ZLD and I was expecting to receive ZLD upon completing tasks. 

However, no ZLD was received after completing a task, and also when the debt "expired".

Maybe payments are not working, or mayne this is due to #1820

**Comment by 0crat** [comment] 2018-12-21 08:35
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-12-21 08:35
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment] 2018-12-28 14:57
@emilianodellacasa Looks like related to https://github.com/zerocracy/farm/issues/1820
Unless you have your wallet set to `zld`.

**Comment by emilianodellacasa** [comment] 2018-12-28 14:58
@krzyk My wallet is set to ZLD actually

**Comment by g4s8** [comment] 2019-01-06 21:47
@emilianodellacasa can you please provide a link to the job where you didn't receive the payment?

**Comment by emilianodellacasa** [comment] 2019-01-07 08:40
@g4s8 https://github.com/zold-io/zold/issues/618 for example

**Comment by g4s8** [comment] 2019-01-10 12:23
@emilianodellacasa do you have debts right now? According to footprint, your debt should be updated last time by `gh:zold-io/zold#654` job, but I can't see this job in your debts, did you receive last debt payment?

**Comment by emilianodellacasa** [comment] 2019-01-10 14:35
@g4s8 No, I don't have any debts now and I know for sure that last debt was not paid at all (this is the reason why I opened this issue)

**Comment by g4s8** [comment] 2019-01-11 13:35
@emilianodellacasa it's versy strange issue, these debt payments were added to ledger, it's the last step of debt payment, so it's possible only if wts API returned success status `303`, don't you know is there any logging system in wts API? The problem here is that wts API doesn't return any transaction id (or something similar), so we are not able to track wts payments. (maybe this issue is related: https://github.com/zold-io/wts.zold.io/issues/66)

@yegor256 please look at this issue, it seems that wts API returned 303 but payment was not received by @emilianodellacasa these payments were added to ledger (transaction ids: `393`, `354`), so is it possible to send it again directly from Zerocracy's ZLD wallet?

**Comment by g4s8** [comment] 2019-01-17 07:39
@emilianodellacasa it seems that wts API is returning 303 status code when payment request added to queue, but Zold network may not accept this payment later.

From Zold chat:
> yegor256, [17.01.19 10:33]
This is not enough. This status only means that WTS accepted your request. But it doesn't mean Zold network accepted it.

> yegor256, [17.01.19 10:34]
WTS returns 302 when your request is in the queue. That's it.

> yegor256, [17.01.19 10:34]
Then, in about 30-50 seconds, you should ask WTS for the status of the job in the queue. And if it's OK, your payment is sent.

> yegor256, [17.01.19 10:34]
This is what wait() method is doing.

**Comment by yegor256** [comment] 2019-01-17 12:16
@g4s8 FYI, this is the error on the server side of WTS:

```
RuntimeError: Wrong details "%40emilianodellacasa%3A+Payment+for+gh%3Azold-io%2Fzold%23356%3A+Order+was+finished%2C+quality+is+%22good%22" ([a-zA-Z0-9 @\!\?\*_\-\.:,'/]+)
  from zold/txn.rb:91:in `initialize'
  from zold/wallet.rb:130:in `new'
  from zold/wallet.rb:130:in `sub'
  from zold/commands/pay.rb:124:in `pay'
  from zold/commands/pay.rb:94:in `block in run'
  from zold/sync_wallets.rb:47:in `block (2 levels) in acq'
  from futex.rb:130:in `block in open'
  from futex.rb:176:in `open_synchronized'
  from futex.rb:103:in `open'
  from zold/sync_wallets.rb:46:in `block in acq'
  from zold/cached_wallets.rb:51:in `block in acq'
  from zold/wallets.rb:71:in `acq'
  from zold/cached_wallets.rb:49:in `acq'
  from zold/sync_wallets.rb:45:in `acq'
  from zold/commands/pay.rb:93:in `run'
  from zold/commands/thread_badge.rb:41:in `run'
  from objects/ops.rb:76:in `block in pay'
  from tempfile.rb:295:in `open'
  from objects/ops.rb:73:in `pay'
  from wts.rb:362:in `block (2 levels) in <top (required)>'
  from wts.rb:775:in `block in job'
  from objects/update_job.rb:47:in `call'
  from objects/clean_job.rb:43:in `call'
  from objects/versioned_job.rb:34:in `call'
  from objects/zache_job.rb:32:in `call'
  from objects/safe_job.rb:35:in `call'
  from objects/async_job.rb:41:in `block (2 levels) in call'
  from futex.rb:130:in `block in open'
  from futex.rb:176:in `open_synchronized'
  from futex.rb:103:in `open'
  from objects/async_job.rb:40:in `block in call'
  from concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
  from concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
  from concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
  from concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
  from concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
  from concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by yegor256** [comment] 2019-01-17 12:18
@g4s8 I would suggest to replace anything that doesn't match the regex `a-zA-Z0-9 @\!\?\*_\-\.:,'/` with a space and then cut off the end, if the line is longer than 128 chars.

**Comment by yegor256** [comment] 2019-01-17 12:22
@g4s8 I will try to fix it a bit in https://github.com/zold-io/wts.zold.io/issues/113

**Comment by g4s8** [comment] 2019-01-17 17:51
@rultor release, tag=`0.40.6`

**Comment by g4s8** [comment] 2019-01-17 17:53
@yegor256 thanks, I added regex `replaceAll("-")` for invalid chars

@emilianodellacasa this issue was reproduced and fixed in https://github.com/zerocracy/farm/commit/c079256c622b4f4d13bbc67edb12f25a3db19d59 it should be available with next release `0.40.6`

**Closed** 2019-02-20 08:40 UTC

**Comment by 0crat** [comment] 2019-02-20 08:57
Job `gh:zerocracy/farm#1833` is not assigned, can't get performer

**Comment by 0crat** [comment] 2019-02-20 08:57
This job is not in scope
