### ISSUE TITLE
0crat didn't reply to "waiting" message

### ISSUE THREAD

**Issue by nikialeksey** [zerocracy/farm#682] opened 2018-03-01 08:03 UTC
I told "waiting" to 0crat, https://github.com/yegor256/cactoos/issues/644#issuecomment-368729877 but it don't reply to me. Then 0crat resigned me.

**Comment by 0crat** [comment] 2018-03-01 08:03
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment] 2018-03-02 06:38
@nikialeksey I think it's a duplicate of #476

**Closed by yegor256** 2018-03-02 06:38 UTC
