### ISSUE TITLE
Bug with reputation receiving

### ISSUE THREAD

**Issue by iakunin** [zerocracy/farm#2157] opened 2019-09-20 10:39 UTC
zerocrat said that `There is no quality review for #1172, no performer`.

https://github.com/yegor256/cactoos/issues/1172#issuecomment-531896622

**Expected behavior**: reputation points successfully accrued to the performer (@iakunin)

**Observed behavior**: there are no reputation points for the issue https://github.com/yegor256/cactoos/issues/1172

**Comment by 0crat** [comment] 2019-09-20 10:39
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-09-20 10:39
@iakunin[/z](https://www.0crat.com/u/iakunin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment] 2019-09-22 14:23
@iakunin thanks for reporting, but it's a duplicate of #2155

**Comment by 0crat** [comment] 2019-09-22 14:24
Job `gh:zerocracy/farm#2157` is not assigned, can't get performer

**Closed by g4s8** 2019-09-22 14:23 UTC
