### ISSUE TITLE
0crat crashed when I tried to invite

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#2142] opened 2019-09-10 08:36 UTC
I typed `/invite @silasreinagel` and 0crat answered me with:
```
There is an unrecoverable failure on my side. Please, submit it here (https://github.com/zerocracy/farm/issues):

PID: 4@1bed83ee-72bd-4b90-b626-859c1bf71176, thread: pool-19-thread-69
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/resumes/resume[@login='silasreinagel']/examiner/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<resumes ..1308..</telegram>\uA   </resume>\uA</resumes>\uA': Index (0) is out of bounds (size=0)


0.49.8 (https://github.com/zerocracy/farm): CID: c4bd596f-f7f8-4de6-8a32-4c5e0f14af73 (https://www.0crat.com/footprint/PMO/c4bd596f-f7f8-4de6-8a32-4c5e0f14af73), Type: "Invite a friend"
```

**Comment by 0crat** [comment] 2019-09-10 08:36
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment] 2019-09-10 08:54
@victornoel thanks for reporting, but it's a duplicate of #2122

**Closed by g4s8** 2019-09-10 08:54 UTC
Labels: join

**Comment by 0crat** [comment] 2019-09-10 08:58
Job `gh:zerocracy/farm#2142` is not assigned, can't get performer
