### ISSUE TITLE
Vesting proof link is broken

### ISSUE THREAD

**Issue by ammaratef45** [zerocracy/farm#2073] opened 2019-06-08 14:11 UTC
When I click on proof word behind vesting share I get the following

>java.lang.IllegalStateException: [GET https://www.0crat.com/equity/CJT4R32Q3] failed in 6s: HTTP response status is not equal to 200:
500 Internal Server Error [https://sheila.infra.cloudconvert.com/download/e3e3cd1b-53dc-4c01-80d0-7abf8b167fd6?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"2a-c5Yd735mWsST6SbM+ozpXm6eIAU"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 42
Date: Sat, 08 Jun 2019 14:08:39 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8
{"error":"Converter not found","code":500}
Expected: HTTP response with status 200
     but: was <500 Internal Server Error [https://sheila.infra.cloudconvert.com/download/e3e3cd1b-53dc-4c01-80d0-7abf8b167fd6?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"2a-c5Yd735mWsST6SbM+ozpXm6eIAU"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 42
Date: Sat, 08 Jun 2019 14:08:39 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8
{"error":"Converter not found","code":500}>
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: HTTP response status is not equal to 200:
500 Internal Server Error [https://sheila.infra.cloudconvert.com/download/e3e3cd1b-53dc-4c01-80d0-7abf8b167fd6?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"2a-c5Yd735mWsST6SbM+ozpXm6eIAU"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 42
Date: Sat, 08 Jun 2019 14:08:39 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8
{"error":"Converter not found","code":500}
Expected: HTTP response with status 200
     but: was <500 Internal Server Error [https://sheila.infra.cloudconvert.com/download/e3e3cd1b-53dc-4c01-80d0-7abf8b167fd6?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"2a-c5Yd735mWsST6SbM+ozpXm6eIAU"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 42
Date: Sat, 08 Jun 2019 14:08:39 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8
{"error":"Converter not found","code":500}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:111)
	at com.zerocracy.tools.Latex.pdf(Latex.java:103)
	at com.zerocracy.pm.cost.Equity.pdf(Equity.java:102)
	at com.zerocracy.tk.project.TkEquity.act(TkEquity.java:73)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:48)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more

**Comment by 0crat** [comment] 2019-06-08 14:11
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-06-08 14:11
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment] 2019-06-08 14:40
@ammaratef45 thanks for reporting but it's a duplicate of https://github.com/zerocracy/farm/issues/852

**Closed by g4s8** 2019-06-08 14:40 UTC

**Comment by 0crat** [comment] 2019-06-08 14:47
Job `gh:zerocracy/farm#2073` is not assigned, can't get performer
