### ISSUE TITLE
Can't invite user

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#2010] opened 2019-04-23 13:06 UTC
I'm having some problems inviting an user via telegram bot:
- `/invite @username` brings me 

> PID: 4@923e652f-f5d1-4012-8b12-ee52dfcefe50, thread: pool-17-thread-54
> com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '/resumes/resume[@login='alessandrosilva']/examiner/text()' not found in '<?xml version="1.0" encoding="UTF-8"?>\uA<resumes ..2580..</telegram>\uA   </resume>\uA</resumes>\uA': Index (0) is out of bounds (size=0)

**Comment by 0crat** [comment] 2019-04-23 13:07
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment] 2019-04-23 13:30
@paulodamaso thanks, but it's a duplicate of #1826

**Closed** 2019-04-24 09:12 UTC
Labels: duplicate

**Comment by 0crat** [comment] 2019-04-24 09:20
Job `gh:zerocracy/farm#2010` is not assigned, can't get performer
