### ISSUE TITLE
Didn't receive payment

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#691] opened 2018-03-02 07:51 UTC
0crat sends me a message:
> 0crat:
We just paid you the debt of $49.16 (AP-16M35497P30599505)

But I didn't receive it via PayPal

**Comment by 0crat** [comment] 2018-03-02 07:51
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment] 2018-03-02 08:51
@g4s8 seems to be the same problem as with #490 I suspect that the prefix `AP-` means that the payment hasn't been sent through and we should throw an exception.

**Comment by yegor256** [comment] 2018-03-02 08:56
@g4s8 I believe it's standing for "adaptive payments", the PayPal API we are using now.

**Comment by yegor256** [comment] 2018-03-02 09:24
@g4s8 I'm closing this as a duplicate of #490 I put 49.16 back to the list of debts for your account.

**Comment by g4s8** [comment] 2018-03-02 09:25
@yegor256 thanks

**Closed by yegor256** 2018-03-02 09:24 UTC
