### ISSUE TITLE
NullPointerException in finish_order.groovy

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#681] opened 2018-03-01 08:00 UTC
Right now `0crat` could not finish any orders. This means no clearing out agendas, no award points and no payments, among other things.

See for example https://github.com/zerocracy/farm/pull/647#issuecomment-369507005

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/finish_order.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
org.cactoos.scalar.Or[154] java.lang.NullPointerException: null
```

**Comment by 0crat** [comment] 2018-03-01 08:00
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by carlosmiranda** [comment] 2018-03-01 08:04
@yegor256 I think this issue is urgent to fix.

**Comment by yegor256** [comment] 2018-03-01 08:14
@carlosmiranda I believe I fixed it already... you still experiencing this?

**Comment by carlosmiranda** [comment] 2018-03-01 08:15
@yegor256 https://github.com/zerocracy/farm/pull/647#issuecomment-369507005 was only 20 minutes ago, do we have a new version released after that?

**Comment by yegor256** [comment] 2018-03-01 08:16
@carlosmiranda hm... let me test and fix. The cause of the problem is this: #615

**Comment by 0crat** [comment] 2018-03-01 08:18
The job [#681](https://github.com/zerocracy/farm/issues/681) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/600818776). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment] 2018-03-01 08:20
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment] 2018-03-01 08:20
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment] 2018-03-01 13:36
@carlosmiranda I disabled the check for now. It will be properly fixed when we have this: #646

**Closed by yegor256** 2018-03-01 13:36 UTC
Labels: scope

**Comment by 0crat** [comment] 2018-03-01 13:39
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment] 2018-03-01 13:40
The job [#681](https://github.com/zerocracy/farm/issues/681) is now out of scope
