### ISSUE TITLE
https://www.0crat.com/join is broken after I filled the form and submitted.

### ISSUE THREAD

**Issue by webdatavisualdev** [zerocracy/farm#2056] opened 2019-05-28 19:42 UTC
I attached the image.
![Screen Shot 2019-05-28 at 12 39 16 PM](https://user-images.githubusercontent.com/29671404/58507223-16b27a00-8146-11e9-95fb-a1677949ef2b.png)

**Comment by 0crat** [comment] 2019-05-28 19:42
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-05-28 19:43
@webdatavisualdev[/z](https://www.0crat.com/u/webdatavisualdev) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by sbzDev** [comment] 2019-05-29 04:44
@g4s8 hi! Might it be related to my recent changes for #1805 ? how can I help with that?

**Comment by g4s8** [comment] 2019-05-29 10:02
@sbzDev this error should be fixed by your changes (but it's not release yet). Actually, we need to check that user has assigned examiner in `TkJoin` and render it **only** if examiner exist. Can you take this ticket?

**Comment by sbzDev** [comment] 2019-05-29 10:08
@g4s8 `xsl/resume.xsl` doesn't have `examiner` also it missed it in `com/zerocracy/tk/TkJoin.java`

```
result = new RsPage(
                this.farm,
                "/xsl/resume.xsl",
                req,
                () -> new XeAppend(
                    "resume",
                    new XeAppend("login", resume.login()),
                    new XeAppend("text", resume.text()),
                    new XeAppend("personality", resume.personality()),
                    new XeAppend("soid", Long.toString(resume.soid())),
                    new XeAppend("telegram", resume.telegram())
                )
            );
```

So actually I don't know how to reproduce it to debug and find root of cause.

**Comment by sbzDev** [comment] 2019-05-29 10:14
@g4s8 I will be happy to help & resolve this issue. Could someone to help me with reproducing/debugging it? how can I check it locally?

**Comment by g4s8** [comment] 2019-05-29 10:25
@sbzDev it's not possible to reproduce because you've fixed this bug already. But now we can't see examiner login in resume. So we need to have an ability to check that examiner exist. I'd not suggest to return default values like `""` from data objects, it would be better to add new method instead, e.g. `hasExaminer` to `Resumes`, similar to `hasMentor` in `People`. To avoid inconsistency you can access same file via transaction:
```java
try (final Txn txn = new Txn(new Pmo(farm))) {
  Resumes resumes = new Resumes(txn);
  if (resumes.hasExaminer(login)) {
    xml.add("examiner" resumes.examiner());
  }
}

**Comment by g4s8** [comment] 2019-05-29 10:25
@0crat assign @sbzDev

**Comment by 0crat** [comment] 2019-05-29 10:28
> @0crat assign @sbzDev  ([here](https://github.com/zerocracy/farm/issues/2056#issuecomment-496879121))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2056](https://github.com/zerocracy/farm/issues/2056), see [§21](http://www.zerocracy.com/policy.html#21); @sbzdev[/z](https://www.0crat.com/u/sbzdev) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment] 2019-05-29 10:32
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by sbzDev** [comment] 2019-05-29 10:32
@g4s8 got it! please assign it to me. and I will prepare PR ASAP

**Comment by 0crat** [comment] 2019-05-29 10:34
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @webdatavisualdev[/z](https://www.0crat.com/u/webdatavisualdev)

**Comment by sbzDev** [comment] 2019-05-29 13:12
@g4s8 PR is ready

**Comment by 0crat** [comment] 2019-05-29 13:12
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9c7f6a11-0968-4021-ae8f-51e6525e5350, thread: pool-95-thread-1
com.jcabi.github.RtValuePagination$Items[181] java.lang.IllegalStateException: java.io.IOException: failed after 4 attempts
com.jcabi.http.wire.RetryWire[95] java.io.IOException: failed after 4 attempts
```

[0.47.4](https://github.com/zerocracy/farm): Issue: zerocracy/farm#2056, Action: `created`

**Comment by sbzDev** [comment] 2019-05-30 08:12
@g4s8 PR is ready

**Comment by sbzDev** [comment] 2019-05-31 12:31
@0crat status

**Comment by 0crat** [comment] 2019-05-31 12:37
> @0crat status ([here](https://github.com/zerocracy/farm/issues/2056#issuecomment-497691795))

@sbzDev This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#2056](https://github.com/zerocracy/farm/issues/2056) is [in scope](http://www.zerocracy.com/policy.html#14) for 2days
  * The role is `DEV`
  * The job is assigned to @sbzdev[/z](https://www.0crat.com/u/sbzdev) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @webdatavisualdev[/z](https://www.0crat.com/u/webdatavisualdev): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%232056%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by sbzDev** [comment] 2019-05-31 12:46
@g4s8 if PR is ok. Can this issue be closed?

**Comment by sbzDev** [comment] 2019-06-01 06:35
@webdatavisualdev please close this issue. The fix is delivered

**Comment by sbzDev** [comment] 2019-06-05 08:10
@sereshqua how can I speed up closing this issue?

**Comment by sereshqua** [comment] 2019-06-05 08:13
@sbzDev hi! you need to tag and ask issue creator to close the issue, because the PR has been already merged. The author is @webdatavisualdev

**Comment by sbzDev** [comment] 2019-06-05 08:15
@sereshqua thanks. I did it 4 days ago.

**Comment by sereshqua** [comment] 2019-06-05 08:20
@sbzDev try to ping him in TG as well

**Closed** 2019-06-05 09:16 UTC
Labels: scope

**Comment by 0crat** [comment] 2019-06-05 09:33
Job [#2056](https://github.com/zerocracy/farm/issues/2056) is not in the agenda of @sbzdev[/z](https://www.0crat.com/u/sbzdev), can't retrieve data and time of add

**Comment by 0crat** [comment] 2019-06-05 09:33
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sbzdev[/z](https://www.0crat.com/u/sbzdev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2019-06-05 09:33
Job [#2056](https://github.com/zerocracy/farm/issues/2056) is not in the agenda of @sbzdev[/z](https://www.0crat.com/u/sbzdev), can't inspect

**Comment by 0crat** [comment] 2019-06-05 09:34
The job [#2056](https://github.com/zerocracy/farm/issues/2056) is now out of scope

**Comment by sereshqua** [comment] 2019-06-05 09:40
@0crat quality good

**Comment by 0crat** [comment] 2019-06-05 09:56
Order was finished, quality is "good": +35 point(s) just awarded to @sbzdev[/z](https://www.0crat.com/u/sbzdev)

**Comment by 0crat** [comment] 2019-06-05 09:56
> @0crat quality good  ([here](https://github.com/zerocracy/farm/issues/2056#issuecomment-499013648))

@sereshqua The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment] 2019-06-05 10:00
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment] 2019-06-05 10:00
> @0crat quality good  ([here](https://github.com/zerocracy/farm/issues/2056#issuecomment-499013648))

@sereshqua The project doesn't have enough funds, can't make a payment
