### ISSUE TITLE
Received points but no payment

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1260] opened 2018-06-27 12:08 UTC
Happened again, received just points but no payment from 0crat.

Performed https://github.com/Harvest-foundation/telegram/pull/81 as `REV`, after merge 0crat paid just point value, and removed task from agenda. 0crat didn't showed any error message though.

May be the same problem of #997.

**Comment by 0crat** [comment] 2018-06-27 12:08
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment] 2018-06-27 19:39
@paulodamaso it's a duplicate of #1188: the project has enough funds to pay you, but payment failed because recharge was failed

**Comment by 0crat** [comment] 2018-06-27 19:39
Job `gh:zerocracy/farm#1260` is not assigned, can't get performer

**Closed by g4s8** 2018-06-27 19:39 UTC
