### ISSUE TITLE
I've lost gains in 0cracy

### ISSUE THREAD

**Issue by ebercamargo** [zerocracy/farm#1973] opened 2019-03-30 14:41 UTC
Hi,

I had several gains in 0cracy, yesterday they disappeared from my account, are not on paypal and are not in my wallet of Zoldy, would like to know how to solve this?

My account is 0cracy: @ebercamargo
Yesterday: 29/03/2019

Sure of the resolution of this inconvenience.

![image](https://user-images.githubusercontent.com/37782410/55289812-b13e4900-53a1-11e9-8259-bd35f616f61f.png)

tks.

**Comment by 0crat** [comment] 2019-03-30 14:41
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-03-30 14:41
@ebercamargo[/z](https://www.0crat.com/u/ebercamargo) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment] 2019-04-01 08:28
@ebercamargo isn't it a duplicate of #1966 bug?

**Comment by ebercamargo** [comment] 2019-04-01 11:37
> @ebercamargo isn't it a duplicate of #1966 bug?

@g4s8 No, this is because of the lack of money.

**Comment by g4s8** [comment] 2019-04-01 12:28
@ebercamargo it's not technically possible to send payment to "nowhere", could you please clarify your problem?

**Comment by ebercamargo** [comment] 2019-04-01 12:42
@g4s8 
1 - I set ocrat bot : /wallet zold 87a77d9144b8034a - this is my wallet in Zold, in accoding http://www.zerocracy.com/policy.html#20
 
![image](https://user-images.githubusercontent.com/37782410/55328021-ced2e780-5461-11e9-8e1e-4698ff6e229b.png)

2 - The bot send my gains to wallet ebercamargo, that did not exist at that time;

3 - And the money was lost.

**Comment by g4s8** [comment] 2019-04-01 12:43
@ebercamargo if you saw the message "We just paid you the debt" with WTS

**Closed by g4s8** 2019-04-01 12:43 UTC

**Comment by ebercamargo** [comment] 2019-04-01 12:47
> @ebercamargo if you saw the message "We just paid you the debt" with WTS job id, then 0crat sent payment to WTS correctly. Please report this bug to WTS repo if you didn't receive it https://github.com/zold-io/wts.zold.io/

@g4s8 Sorry but the problem is the bot, he can not send to a wallet that was not informed to him.

**Comment by g4s8** [comment] 2019-04-01 12:56
@ebercamargo most probably you've changed your wallet for `zold` what is not valid address, so it's a duplicate of https://github.com/zerocracy/farm/issues/1966

**Comment by 0crat** [comment] 2019-04-01 13:01
Job `gh:zerocracy/farm#1973` is not assigned, can't get performer

**Comment by 0crat** [comment] 2019-04-01 13:01
This job is not in scope
