### ISSUE TITLE
java.lang.NumberFormatException

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1537] opened 2018-08-03 05:31 UTC
I just got it here: https://github.com/zold-io/zold.github.io/issues/76#issuecomment-410148642:

```
PID: 4@25fbab20-c312-42db-aced-b573bac3c501, thread: pool-19-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-03T05:44:34.785Z"
```

**Comment by 0crat** [comment] 2018-08-03 05:31
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-08-03 11:27
Job [#1537](https://github.com/zerocracy/farm/issues/1537) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-08-03 11:33
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by filfreire** [comment] 2018-08-03 12:17
@yegor256 I also got it here, after closing an issue:
https://github.com/yegor256/tacit/issues/153#issuecomment-410235395

```
PID: 4@25fbab20-c312-42db-aced-b573bac3c501, thread: pool-401-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-03T12:29:24.119Z"
```

**Comment by paulodamaso** [comment] 2018-08-03 12:29
@yegor256 I think it's a duplicate of https://github.com/zerocracy/farm/issues/1528

**Comment by krzyk** [comment] 2018-08-04 21:09
@paulodamaso I don't think so, I got it again here: https://github.com/Harvest-foundation/telegram/issues/149#issuecomment-410477698
So after manual close of a bug (a blank one).

**Comment by g4s8** [comment] 2018-08-05 11:53
@0crat assign me

**Comment by 0crat** [comment] 2018-08-05 12:05
> @0crat assign me ([here](https://github.com/zerocracy/farm/issues/1537#issuecomment-410515133))

@g4s8 The job [#1537](https://github.com/zerocracy/farm/issues/1537) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2171213135); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by g4s8** [comment] 2018-08-05 15:31
stacktrace:
```
2018-08-05T15:31:06.708514+00:00 app[web.1]: BUILD pool-15-thread-1 com.zerocracy.radars.github.RbSafe: Issue: zerocracy/farm#1522, Action: `closed`, error: java.lang.NumberFormatException: For input string: "2018-08-05T15:46:06.66Z"
2018-08-05T15:31:06.708522+00:00 app[web.1]: at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
2018-08-05T15:31:06.708524+00:00 app[web.1]: at java.lang.Long.parseLong(Long.java:589)
2018-08-05T15:31:06.708525+00:00 app[web.1]: at java.lang.Long.parseLong(Long.java:631)
2018-08-05T15:31:06.708527+00:00 app[web.1]: at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
2018-08-05T15:31:06.708529+00:00 app[web.1]: at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
2018-08-05T15:31:06.708530+00:00 app[web.1]: at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
2018-08-05T15:31:06.708532+00:00 app[web.1]: at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
2018-08-05T15:31:06.708534+00:00 app[web.1]: at org.cactoos.iterator.Mapped.next(Mapped.java:70)
2018-08-05T15:31:06.708535+00:00 app[web.1]: at org.cactoos.iterator.ItemAt.value(ItemAt.java:146)
2018-08-05T15:31:06.708537+00:00 app[web.1]: at org.cactoos.iterable.ItemAt.value(ItemAt.java:142)
2018-08-05T15:31:06.708539+00:00 app[web.1]: at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
2018-08-05T15:31:06.708540+00:00 app[web.1]: at com.zerocracy.claims.ClaimsSqs.submit(ClaimsSqs.java:85)
2018-08-05T15:31:06.708541+00:00 app[web.1]: at com.zerocracy.entry.ValidClaims.submit(ValidClaims.java:68)
2018-08-05T15:31:06.708543+00:00 app[web.1]: at com.zerocracy.entry.ClaimsOf.submit(ClaimsOf.java:95)
2018-08-05T15:31:06.708545+00:00 app[web.1]: at com.zerocracy.claims.ClaimOut.postTo(ClaimOut.java:107)
2018-08-05T15:31:06.708546+00:00 app[web.1]: at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:84)
2018-08-05T15:31:06.708548+00:00 app[web.1]: at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:63)
2018-08-05T15:31:06.708549+00:00 app[web.1]: at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:78)
2018-08-05T15:31:06.708551+00:00 app[web.1]: at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
2018-08-05T15:31:06.708552+00:00 app[web.1]: at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:84)
2018-08-05T15:31:06.708554+00:00 app[web.1]: at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:59)
2018-08-05T15:31:06.708555+00:00 app[web.1]: at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
2018-08-05T15:31:06.708557+00:00 app[web.1]: at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:59)
2018-08-05T15:31:06.708558+00:00 app[web.1]: at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:111)
2018-08-05T15:31:06.708560+00:00 app[web.1]: at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:50)
2018-08-05T15:31:06.708561+00:00 app[web.1]: at com.zerocracy.radars.github.RbDelayed.react(RbDelayed.java:55)
2018-08-05T15:31:06.708562+00:00 app[web.1]: at com.zerocracy.radars.github.RbAccessible.react(RbAccessible.java:86)
2018-08-05T15:31:06.708564+00:00 app[web.1]: at com.zerocracy.radars.github.RbSync.react(RbSync.java:48)
2018-08-05T15:31:06.708565+00:00 app[web.1]: at com.zerocracy.radars.github.RbAsync.lambda$react$0(RbAsync.java:49)
2018-08-05T15:31:06.708567+00:00 app[web.1]: at org.cactoos.func.AsyncFunc.lambda$apply$0(AsyncFunc.java:120)
2018-08-05T15:31:06.708568+00:00 app[web.1]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-08-05T15:31:06.708570+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2018-08-05T15:31:06.708571+00:00 app[web.1]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-08-05T15:31:06.708573+00:00 app[web.1]: at java.lang.Thread.run(Thread.java:748)
2018-08-05T15:31:06.708574+00:00 app[web.1]: 
```

**Comment by g4s8** [comment] 2018-08-05 17:04
@rultor release, tag=`0.29.6`

**Comment by g4s8** [comment] 2018-08-05 17:43
@rultor release, tag=`0.29.6`

**Comment by g4s8** [comment] 2018-08-05 18:45
@yegor256 this bug was reproduced and fixed in https://github.com/zerocracy/farm/commit/f562b4140ae192eb065b77ac0d4ab25746a8813a, the fix was released in `0.29.6`, can we close?

**Comment by g4s8** [comment] 2018-08-12 20:17
@yegor256 this bug is not reproducing anymore (after fix in https://github.com/zerocracy/farm/commit/f562b4140ae192eb065b77ac0d4ab25746a8813a).

**Closed by g4s8** 2018-08-12 20:17 UTC
Labels: bug, scope

**Comment by 0crat** [comment] 2018-08-12 20:35
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment] 2018-08-12 20:35
The job [#1537](https://github.com/zerocracy/farm/issues/1537) is now out of scope
