### ISSUE TITLE
0crat is not paying architect release bonus

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1817] opened 2018-12-06 20:17 UTC
Today I released tag 1.11.4 in https://github.com/yegor256/takes/issues/838#issuecomment-444944098 for project takes, but the release bonus (http://www.zerocracy.com/policy.html#54) does  not appear in my wallet. I have no traces of it even in slack chat, looks like zerocrat just forgot to pay me for this release.

**Comment by 0crat** [comment] 2018-12-06 20:17
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment] 2018-12-07 06:45
@paulodamaso The claim to pay you for release was submitted successfully, see https://www.0crat.com/footprint/C3FFK3YAY/a223a63a-d5c2-4bcc-9a9e-e4f63c11e120
but the project doesn't have enough cash to pay you, so cash payments was ignored (you've received only reputation points and Zold bonus). So it's not Zerocracy bug, to fix it you may ask PO to fund the project.

**Comment by paulodamaso** [comment] 2018-12-07 10:18
@g4s8 All right, so I think that 0crat should say something like "Not enough funds" or something. Another doubt, all failed payments due no funding are lost then?

**Comment by paulodamaso** [comment] 2019-06-08 22:50
@g4s8 Happened again, this time on [stryv] (https://www.0crat.com/p/GFV03LPPY) project even when project had funding:
![stryv_arc_release](https://user-images.githubusercontent.com/33915433/59153008-6f2b2680-8a26-11e9-83bc-d53953a6364c.jpg)

According to rate, release bonus should be $140 (120 mins). This money was available at the funding that time.

**Comment by g4s8** [comment] 2019-06-10 20:22
@paulodamaso looks like Mongo is getting slower with new projects https://www.0crat.com/footprint/GFV03LPPY/6c37deb2-9b70-4655-a4cb-0087261d49ce

related to: https://github.com/zerocracy/farm/issues/829

```
com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message
	at com.mongodb.internal.connection.InternalStreamConnection.translateReadException(InternalStreamConnection.java:537)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:428)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:289)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:242)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:233)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:136)
	at com.mongodb.operation.AggregateOperationImpl$1.call(AggregateOperationImpl.java:193)
	at com.mongodb.operation.AggregateOperationImpl$1.call(AggregateOperationImpl.java:189)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:457)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:401)
	at com.mongodb.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:189)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:294)
	at com.mongodb.operation.CountOperation.execute(CountOperation.java:242)
	at com.mongodb.operation.CountOperation.execute(CountOperation.java:66)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:179)
	at com.mongodb.client.internal.MongoCollectionImpl.executeCount(MongoCollectionImpl.java:248)
	at com.mongodb.client.internal.MongoCollectionImpl.countDocuments(MongoCollectionImpl.java:217)
	at com.mongodb.client.internal.MongoCollectionImpl.countDocuments(MongoCollectionImpl.java:212)
	at com.mongodb.client.MongoCollection$countDocuments.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at com.zerocracy.stk.pm.cost.pay_architect_for_release$_exec_closure1.doCall(pay_architect_for_release.groovy:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withCloseable(IOGroovyMethods.java:1630)
	at org.codehaus.groovy.runtime.NioGroovyMethods.withCloseable(NioGroovyMethods.java:1759)
	at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
	at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:56)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at com.zerocracy.stk.pm.cost.pay_architect_for_release.exec(pay_architect_for_release.groovy:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:46)
	at groovy.lang.Script.invokeMethod(Script.java:80)
	at com.zerocracy.farm.reactive.StkRuntime.process(StkRuntime.java:63)
	at com.zerocracy.farm.StkTimed.process(StkTimed.java:67)
	at com.zerocracy.farm.StkVerbose.process(StkVerbose.java:59)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:99)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:64)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:80)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:62)
```

**Comment by 0crat** [comment] 2019-06-10 20:26
Job [#1817](https://github.com/zerocracy/farm/issues/1817) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2019-06-10 20:33
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment] 2019-06-14 21:37
@g4s8 Happened again in the same project, please check

**Comment by g4s8** [comment] 2019-08-07 12:32
@paulodamaso duplicate of #2013

**Closed by g4s8** 2019-08-07 12:32 UTC
Labels: bug, scope

**Comment by 0crat** [comment] 2019-08-07 13:12
Job `gh:zerocracy/farm#1817` is not assigned, can't get performer

**Comment by 0crat** [comment] 2019-08-07 13:15
The job [#1817](https://github.com/zerocracy/farm/issues/1817) is now out of scope
