### ISSUE TITLE
The com.zerocracy.tk.profile.TkProfileTest#showsLinkToPolicyForUnknownUser test is failing on the AppVeyor

### ISSUE THREAD

**Issue by denis-konovalyenko** [zerocracy/farm#1727] opened 2018-09-26 12:28 UTC
Below is the extracted stack trace of the issue (the full build information is available [here](https://ci.appveyor.com/project/yegor256/farm/build/1100)):

```
com.zerocracy.tk.profile.TkProfileTest
showsLinkToPolicyForUnknownUser(com.zerocracy.tk.profile.TkProfileTest)  Time elapsed: 0.112 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: a string containing "@nvseenu is not invited to us yet, see <a href=\"www.zerocracy.com/policy.html#1\">�1</a>"
     but: was "<!DOCTYPE html
  SYSTEM "about:legacy-compat">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></meta>
      <meta charset="utf-8"></meta>
      <meta name="description" content="Zerocrat is a project manager that never sleeps"></meta>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      <link rel="shortcut icon" href="/png/logo.png"></link>
      <link rel="stylesheet" href="/css/main.css"></link><script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/sortable/0.8.0/js/sortable.min.js"> </script><title>0crat</title>
   </head>
   <body>
      <section>
         <p class="flash flash-WARNING">@nvseenu is not invited to us yet, see <a href="www.zerocracy.com/policy.html#1">§1</a></p>
         <div class="center">
            <p><a href="http://www.example.com/"><img src="/svg/zerocrat.svg" style="height:128px;"></img></a></p>
            <p>Zerocrat is a project manager that <a href="http://www.yegor256.com/2018/03/21/zerocracy-announcement.html">never sleeps</a>.
            </p>
            <nav>
               <ul>
                  <li><a href="/u/yegor256"><span title="GitHub user currently logged in">@yegor256</span></a></li>
                  <li><a href="http://www.zerocracy.com/policy.html">Policy</a></li>
                  <li><a href="http://www.zerocracy.com/terms.html">Terms</a></li>
                  <li>
                     <form action="http://www.example.com/?PsByFlag=PsLogout" method="post" class="form-as-link"><button type="submit" class="link">Exit</button></form>
                  </li>
               </ul>
            </nav>
            <footer>
               <nav>
                  <ul>
                     <li><span title="The bot was deployed manually, without any specific version">?</span></li>
                     <li title="The time since the last restart">3min</li>
                     <li><span title="The time server took to generate this page" class="millis millis-fast">3ms</span></li>
                     <li><span title="Load average at the server" class="sla sla-normal">-1.000</span></li>
                     <li><span title="Used memory on the server versus the total available" class="memory">497/712</span></li>
                  </ul>
               </nav>
            </footer>
         </div>
      </section>
   </body>
</html>"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.zerocracy.tk.profile.TkProfileTest.showsLinkToPolicyForUnknownUser(TkProfileTest.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
@krzyk , assumes that the fix is here https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/issues/45.

**Comment by 0crat** [comment] 2018-09-26 12:28
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment] 2018-09-26 13:42
@denis-konovalyenko duplicate of #1704

**Closed by g4s8** 2018-09-26 13:42 UTC

**Comment by 0crat** [comment] 2018-09-26 14:06
Job `gh:zerocracy/farm#1727` is not assigned, can't get performer
