### ISSUE TITLE
Add support to AppVeyor

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/farm#473] opened 2018-01-26 04:23 UTC
Let's add support to [AppVeyor](https://www.appveyor.com/) CI.

**Comment by 0crat** [comment] 2018-01-26 04:23
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment] 2018-01-26 12:17
@fabriciofx each ticket has to sound like a bug, not a task, see: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5-report-when-it-is-broken

**Comment by g4s8** [comment] 2018-06-13 12:38
@fabriciofx duplicate of #1042

**Closed** 2018-06-13 12:38 UTC

**Comment by 0crat** [comment] 2018-06-13 12:55
The job is not in WBS, won't close the order

**Comment by 0crat** [comment] 2018-06-13 12:55
Job `gh:zerocracy/farm#473` is not assigned, can't get performer
