### ISSUE TITLE
0crat: CRITICAL BUG - Paying WRONG amounts for completed jobs

### ISSUE THREAD

**Issue by SilasReinagel** [zerocracy/farm#2151] opened 2019-09-11 17:24 UTC
This has happened multiple times now!

1. Ticket is boosted to 1x (**15 minutes**). 
2. 0crat approved the boost.
3. 0crat assigns the job with **wrong** budget amount (30 minutes).
4. 0crat pays for **30 minutes** of work, plus 5 minutes speed bonus.

Examples: 
https://github.com/EnigmaDragons/ProjectNeon/issues/7
https://github.com/EnigmaDragons/ProjectNeon/issues/8

![image](https://user-images.githubusercontent.com/10834339/64719897-154f5800-d47e-11e9-81db-5ec3dd2ab85e.png)

Attached is the project ledger showing payed out amounts. Rate for DEV is $35.

[ledger_CN3V1M4AU.zip](https://github.com/zerocracy/farm/files/3601994/ledger_CN3V1M4AU.zip)

**Comment by 0crat** [comment] 2019-09-11 17:24
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-09-11 17:24
@silasreinagel[/z](https://www.0crat.com/u/silasreinagel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment] 2019-09-11 17:39
@SilasReinagel it's a known issue: 0crat resets boost factor when the job gets new assignee. Duplicate of #1400

**Closed by g4s8** 2019-09-11 17:39 UTC
Labels: duplicate

**Comment by 0crat** [comment] 2019-09-11 17:44
Job `gh:zerocracy/farm#2151` is not assigned, can't get performer
