### ISSUE TITLE
Identification via Yoti is broken (again :)

### ISSUE THREAD

**Issue by vassilevsky** [zerocracy/farm#2023] opened 2019-04-30 18:24 UTC
Hello :)

I've identified myself via Yoti and saw this:

Internal application error
0.46.7, ${buildNumber}

Please, report it here. We will do our best to fix it as soon as possible. We're very sorry.

```
java.lang.IllegalStateException: [GET https://www.0crat.com/yoti?token=Fugwu3QTj5REilF5t821nPgijF0wTiJiluXPBff2Cy2VZ...] failed in 1s: null
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.zerocracy.tk.profile.TkYoti.act(TkYoti.java:86)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:48)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
```

Damn nulls are everywhere!

Wat do

**Comment by 0crat** [comment] 2019-04-30 18:24
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-04-30 18:24
@vassilevsky[/z](https://www.0crat.com/u/vassilevsky) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by vassilevsky** [comment] 2019-04-30 18:28
Remind me later :D

**Comment by vassilevsky** [comment] 2019-04-30 18:29
I tried again after 16 minutes and the result was the same. I guess you could say it's reliably broken! :)

**Comment by g4s8** [comment] 2019-04-30 19:17
@vassilevsky thanks for reporting, it's a duplicate of #1977

**Closed by g4s8** 2019-04-30 19:17 UTC
Labels: duplicate

**Comment by 0crat** [comment] 2019-04-30 19:19
Job `gh:zerocracy/farm#2023` is not assigned, can't get performer
