### ISSUE TITLE
Ticket titles in agenta, part 2

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#834] opened 2018-03-19 08:12 UTC
Originated from https://github.com/zerocracy/farm/issues/422. The title was implemented as a mandatory attribute in agenda.xsd model, [here](https://github.com/zerocracy/datum/pull/331). We need to continue implementation as suggested by Yegor [here](https://github.com/zerocracy/farm/pull/784#issuecomment-372447596). 

I opened a ticket rather than making a PR just to leave a puzzle in the code because it's cheaper and faster for the project.

**Comment by 0crat** [comment] 2018-03-19 08:12
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment] 2018-03-19 12:56
@amihaiemil looks like a duplicate of #422. Why do we need a new ticket?

**Closed by yegor256** 2018-03-19 12:56 UTC

**Comment by amihaiemil** [comment] 2018-03-19 13:08
@yegor256 because #422 should be closed now, I've done 30min work with the first PR and then working on datum to add the title attribute. 

Since #422 needs to be closed, we need a ticket to continue implementation, since it's not finished. Either I make a PR in /farm with a puzzle, or open an Issue. I opted for openning this Issue since it's faster and cheaper -- project only pays 15min for the author; if I make a PR, project pays 15min for reviewer, 10min ARC and 8min QA.

**Comment by 0crat** [comment] 2018-03-19 13:11
The job is not in WBS, won't close the order

**Comment by yegor256** [comment] 2018-03-19 13:12
@amihaiemil don't worry about costs, let's follow the procedure
