### ISSUE TITLE
delete awards that are older than 90 days

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#111] opened 2017-07-25 07:17 UTC
We must automatically delete awards that are older than 90 days. Let's do it every time we fetch awards from `Awards`. Also, let's add a notice text to the `/u/<name>/awards` page that "Only the last 90 days are taken into account, older awards are ignored".

**Comment by 0crat** [comment] 2018-02-02 06:10
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#111](https://github.com/zerocracy/farm/issues/111), please stop working

**Comment by 0crat** [comment] 2018-02-10 13:54
The job [#111](https://github.com/zerocracy/farm/issues/111) assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/411354155). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by neonailol** [comment] 2018-02-17 09:50
@0crat waiting

**Comment by 0crat** [comment] 2018-02-17 09:52
> @0crat waiting ([here](https://github.com/zerocracy/farm/issues/111#issuecomment-366430115))

@neonailol The impediment for [#111](https://github.com/zerocracy/farm/issues/111) was registered successfully by @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by neonailol** [comment] 2018-02-24 13:14
@yegor256 i think better to implement it when we add award to a user, do you agree?

**Comment by yegor256** [comment] 2018-02-26 19:49
@neonailol not really. Imagine a situation when a user earned something a month ago and stopped working. We won't remove those awards ever, because no new awards are coming in. Instead, we should regularly check all users (on `Ping daily` or `Ping hourly`) and remove their expired awards.

**Comment by neonailol** [comment] 2018-03-09 09:28
@0crat refuse

**Comment by 0crat** [comment] 2018-03-09 09:29
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/111#issuecomment-371760313))

@neonailol The user @neonailol[/z](https://www.0crat.com/u/neonailol) resigned from [#111](https://github.com/zerocracy/farm/issues/111), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-03-09 09:29
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by g4s8** [comment] 2018-03-09 10:40
@yegor256 seems to be a duplicate of #386

**Comment by 0crat** [comment] 2018-03-09 10:52
The job [#111](https://github.com/zerocracy/farm/issues/111) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/681053638). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by yegor256** [comment] 2018-03-09 14:40
@0crat refuse

**Comment by yegor256** [comment] 2018-03-09 14:40
@0crat out

**Comment by 0crat** [comment] 2018-03-09 14:40
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/111#issuecomment-371830633))

@yegor256 The user @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#111](https://github.com/zerocracy/farm/issues/111), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-03-09 14:41
> @0crat out ([here](https://github.com/zerocracy/farm/issues/111#issuecomment-371830648))

@yegor256 GitHub issue is still open, won't close

**Closed** 2018-03-09 14:41 UTC
Labels: bug

**Comment by 0crat** [comment] 2018-03-09 14:56
The job [#111](https://github.com/zerocracy/farm/issues/111) is now out of scope
