### ISSUE TITLE
Payment is broken

### ISSUE THREAD

**Issue by SharplEr** [zerocracy/farm#643] opened 2018-02-25 11:05 UTC
I had got following message from 0crat:

```
We just paid you $9.33 (AP-7M30975162102181T) for #599: Order was finished, quality was "good"
GitHub
Wrong count files in Directory · Issue #599 · yegor256/cactoos
org.cactoos.io.DirectoryTest:
@Test
public void listsFilesInDirectory() throws IOException {
final Path dir = Files.createTempDirectory...
```

But there isn't such payment on my PayPal history. And my account balance remain intact. But three previous transaction was successful and I haven't changed any settings.

Wallet: sharplermc@gmail.com

So my question is where is my money?)

Also we need to have some command for 0crat to get payment history with transactions id. Because it can be problem on PayPal side.

**Comment by 0crat** [comment] 2018-02-25 11:06
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment] 2018-02-25 19:19
@SharplEr have no idea why and how this could happen... PayPal returned the transaction ID (`AP-7M30975162102181T`) but I can't find it in our account either... We had a similar problem before, I believe https://github.com/zerocracy/farm/issues/490 Looks like this ticket is a duplicate of #490

**Closed by yegor256** 2018-02-25 19:19 UTC
