### ISSUE TITLE
Agenda page show plain html code

### ISSUE THREAD

**Issue by VsSekorin** [zerocracy/farm#901] opened 2018-04-08 06:45 UTC
Agenda page show plain html code:
```text
<body xmlns="http://www.w3.org/1999/xhtml"> <section> <h1>Your Agenda</h1> <p>This is the full list of 3 jobs currently assigned to you in all projects we are managing. Zerocrat adds jobs here automatically. This list is presented for the sake of your convenience.</p> <table data-sortable="true"> <thead> <tr> <th>Job</th> <th>Title</th> <th>Project</th> <th>Added</th> <th>Role</th> <th>Cost<sub>/<a href="http://www.zerocracy.com/policy.html#4">§4</a> </sub> </th> <th>Imp.<sub>/<a href="http://www.zerocracy.com/policy.html#9">§9</a> </sub> </th> </tr> </thead> <tbody> <tr> <td> <a href="https://github.com/yegor256/cactoos-http/issues/8" title="Issue #8 in yegor256/cactoos-http GitHub repository">yegor256/cactoos-http#8</a> </td> <td>-</td> <td> <code style="background-color:#daf1e0;"> <a href="https://www.0crat.com/p/C63314D6Z" title="Project C63314D6Z">C63314D6Z</a> </code> </td> <td> <span title="$ ago at 2018-04-04T13:03:40.11Z">4 days</span> </td> <td> <code style="background-color:#daf1e0;">DEV</code> </td> <td style="text-align:right">$8.00</td> <td>on hold</td> </tr> <tr> <td> <a href="https://github.com/yegor256/cactoos-http/issues/5" title="Issue #5 in yegor256/cactoos-http GitHub repository">yegor256/cactoos-http#5</a> </td> <td>-</td> <td> <code style="background-color:#daf1e0;"> <a href="https://www.0crat.com/p/C63314D6Z" title="Project C63314D6Z">C63314D6Z</a> </code> </td> <td> <span title="$ ago at 2018-04-04T12:29:13.522Z">4 days</span> </td> <td> <code style="background-color:#daf1e0;">DEV</code> </td> <td style="text-align:right">$8.00</td> <td>on hold</td> </tr> <tr> <td> <a href="https://github.com/yegor256/cactoos-http/issues/4" title="Issue #4 in yegor256/cactoos-http GitHub repository">yegor256/cactoos-http#4</a> </td> <td>-</td> <td> <code style="background-color:#daf1e0;"> <a href="https://www.0crat.com/p/C63314D6Z" title="Project C63314D6Z">C63314D6Z</a> </code> </td> <td> <span title="$ ago at 2018-04-04T12:26:40.672Z">4 days</span> </td> <td> <code style="background-color:#daf1e0;">DEV</code> </td> <td style="text-align:right">$8.00</td> <td>on hold</td> </tr> </tbody> </table> </section> </body>
```

Here: https://www.0crat.com/u/VsSekorin/agenda

**Comment by 0crat** [comment] 2018-04-08 06:46
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-04-08 06:46
@vssekorin[/z](https://www.0crat.com/u/vssekorin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment] 2018-04-09 08:50
@VsSekorin what is the browser type/version?

**Comment by VsSekorin** [comment] 2018-04-09 18:02
Firefox Quantum 59.0.2 (64-bit)

**Comment by VsSekorin** [comment] 2018-04-09 18:02
@yegor256 Firefox Quantum 59.0.2 (64-bit)

**Comment by yegor256** [comment] 2018-04-10 09:42
@VsSekorin it's a duplicate of #402

**Closed by yegor256** 2018-04-10 09:42 UTC

**Comment by 0crat** [comment] 2018-04-10 09:57
The job is not in WBS, won't close the order
