### ISSUE TITLE
Student should see how to contact mentor

### ISSUE THREAD

**Issue by korthout** [zerocracy/farm#1870] opened 2019-01-27 13:48 UTC
According to the FAQ page
> If you have any non-technical questions, ask your mentor.

The mentor's zerocrat page only shows the Github user associated to the mentor, but no way to contact the mentor. A student should be able to contact the mentor. A possible solution would be to show the Telegram account associated to the mentor, only visible to the student.

**Comment by 0crat** [comment] 2019-01-27 13:48
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-01-27 13:48
@korthout[/z](https://www.0crat.com/u/korthout) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment] 2019-02-21 16:41
@korthout thanks for reporting, but it's a duplicate of #1828

**Closed by g4s8** 2019-02-21 16:41 UTC
Labels: join

**Comment by 0crat** [comment] 2019-02-21 17:59
Job `gh:zerocracy/farm#1870` is not assigned, can't get performer

**Comment by 0crat** [comment] 2019-02-21 17:59
This job is not in scope
