### ISSUE TITLE
BundlesTest silently swallows exceptions

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#733] opened 2018-03-06 07:59 UTC
In PR #719 we [tried to add](https://github.com/amihaiemil/farm/commit/dbb6001b0c217574d0b6734d0671304767e8bbc3#diff-6b470f91f81f74907161407bc05e83b3) the Github user's followers count to a message. However, MkUser does not have the element ``followersCount`` so IllegalStateException was thrown in the ``assign_role`` bundle test -- but this exception was silently swallowed and displayed in the console output, the test passed fine. 

What is strange is that that exception is not logged in the Travis [build of that commit](https://travis-ci.org/zerocracy/farm/builds/348949245?utm_source=github_status&utm_medium=notification), I only noticed it locally. Instead, in the Travis build we can notice other IllegalStateExceptions which may indicate the same bug.

**Comment by 0crat** [comment] 2018-03-06 07:59
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-03-06 13:00
Job [#733](https://github.com/zerocracy/farm/issues/733) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-03-06 13:01
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment] 2018-04-12 01:38
The job [#733](https://github.com/zerocracy/farm/issues/733) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1020137751); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment] 2018-04-17 02:36
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment] 2018-04-27 07:29
@0crat refuse

**Comment by 0crat** [comment] 2018-04-27 07:30
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/733#issuecomment-384889324))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#733](https://github.com/zerocracy/farm/issues/733), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-04-27 07:30
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by krzyk** [comment] 2018-05-21 19:29
@0crat refuse

**Comment by 0crat** [comment] 2018-05-21 19:30
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/733#issuecomment-390757484))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#733](https://github.com/zerocracy/farm/issues/733), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-05-21 19:30
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment] 2018-05-31 08:12
The job [#733](https://github.com/zerocracy/farm/issues/733) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1510812979); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@434a4c45

**Comment by t-izbassar** [comment] 2018-06-02 16:28
@0crat refuse

**Comment by 0crat** [comment] 2018-06-02 16:29
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/733#issuecomment-394099434))

@t-izbassar The user @t-izbassar[/z](https://www.0crat.com/u/t-izbassar) resigned from [#733](https://github.com/zerocracy/farm/issues/733), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-06-02 16:29
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment] 2018-06-04 08:42
The job [#733](https://github.com/zerocracy/farm/issues/733) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1550842203); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by amihaiemil** [comment] 2018-06-05 06:43
@carlosmiranda Is the change in assign_role.groovy still there? I think the Github ``User`` logic has been moved somewhere else.

You could modify ``assign_role.groovy`` locally as I did [here](https://github.com/amihaiemil/farm/commit/dbb6001b0c217574d0b6734d0671304767e8bbc3#diff-6b470f91f81f74907161407bc05e83b3), run the build and check the logs. Did you do that?

**Comment by 0crat** [comment] 2018-06-09 12:36
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment] 2018-06-10 23:15
@0crat wait for completion, currently busy on other tasks

**Comment by 0crat** [comment] 2018-06-10 23:16
> @0crat wait for completion, currently busy on other tasks ([here](https://github.com/zerocracy/farm/issues/733#issuecomment-396089732))

@carlosmiranda The impediment for [#733](https://github.com/zerocracy/farm/issues/733) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment] 2018-06-26 00:35
@0crat refuse (can't reproduce, so I couldn't work on it)

**Comment by 0crat** [comment] 2018-06-26 00:35
> @0crat refuse (can't reproduce, so I couldn't work on it) ([here](https://github.com/zerocracy/farm/issues/733#issuecomment-400138777))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#733](https://github.com/zerocracy/farm/issues/733), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-06-26 00:36
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment] 2018-07-09 13:04
The job [#733](https://github.com/zerocracy/farm/issues/733) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1901303810); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by carlosmiranda** [comment] 2018-07-09 23:35
@0crat status

**Comment by 0crat** [comment] 2018-07-09 23:37
> @0crat status ([here](https://github.com/zerocracy/farm/issues/733#issuecomment-403652440))

@carlosmiranda This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#733](https://github.com/zerocracy/farm/issues/733) is [in scope](http://www.zerocracy.com/policy.html#14) for 4mon
  * The role is `DEV`
  * The job is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) for [11hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23733%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by mcmillanrabecca27** [comment] 2018-07-09 23:45
On Jul 9, 2018 5:37 PM, "Zerocrat" <notifications@github.com> wrote:

@0crat <https://github.com/0crat> status (here
<https://github.com/zerocracy/farm/issues/733#issuecomment-403652440>)

@carlosmiranda <https://github.com/carlosmiranda> This is what I know about
this job in C3NDPUA8L <https://www.0crat.com/p/C3NDPUA8L>, as in §32
<http://www.zerocracy.com/policy.html#32>:

   - The job #733 <https://github.com/zerocracy/farm/issues/733> is in scope
   <http://www.zerocracy.com/policy.html#14> for 4mon
   - The role is DEV
   - The job is assigned to @carlosmiranda
   <https://github.com/carlosmiranda>/z
   <https://www.0crat.com/u/carlosmiranda> for 11hr
   <http://www.zerocracy.com/policy.html#8>
   - There is a monetary reward attached
   - @carlosmiranda <https://github.com/carlosmiranda>/z
   <https://www.0crat.com/u/carlosmiranda> will get 50% of their hourly
   rate for this job
   - Some equity will be vested <http://www.zerocracy.com/policy.html#37>
   on completion
   - The job doesn't have any impediments
   <http://www.zerocracy.com/policy.html#9>
   - The budget <http://www.zerocracy.com/policy.html#4> is 30
   minutes/points
   - Job footprint
   <https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Ffarm%23733%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D>
   (restricted area)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zerocracy/farm/issues/733#issuecomment-403652726>, or mute
the thread

**Comment by 0crat** [comment] 2018-07-09 23:45
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/733#issuecomment-403653956); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by carlosmiranda** [comment] 2018-07-16 00:46
@0crat refuse (already refused [before}(https://github.com/zerocracy/farm/issues/733#issuecomment-400138821))

**Comment by 0crat** [comment] 2018-07-16 05:57
> @0crat refuse (already refused [before}(https://github.com/zerocracy/farm/issues/733#issuecomment... ([here](https://github.com/zerocracy/farm/issues/733#issuecomment-405130592))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#733](https://github.com/zerocracy/farm/issues/733), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-07-16 06:01
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by paulodamaso** [comment] 2018-07-20 04:20
@amihaiemil I've found that `notify.groovy` is swallowing these exceptions. When we test `assign_role.groovy` it generates other claims with the `test` channel, and unfortunately the exceptions raised in `assign_role.groovy` are wrapped in claims directed to the `test` channel too. So, they're proccessed by `notify.groovy` and redirected to `notify_test.groovy`, which saves them to some text file.

The problem is that our tests are generating claims with the `test` channel, and we don't have how to know if they're the result of expected claim processing or they wrap some exception in the test, preventing the tests to fail.

**Comment by paulodamaso** [comment] 2018-07-20 04:40
@amihaiemil All the magic is happening in `StkSafe:93`: when any groovy scripts thows a `SoftException` it adds a `Notify` claim with the claim that generated the exception and the exception message.

A solution would be tamper with the xml and replace `test` channel with another type, `text-exception` for example, add this channel to `notify.groovy` an explode it there. It will break a lot of tests though. @g4s8 how should we treat this?

**Comment by amihaiemil** [comment] 2018-07-20 09:17
@paulodamaso I would make a PR with a puzzle reflecting what we have to do to fix this problem, or the general direction towards fixing the issue. This, considering that you already spent your time here doing the research.

**Comment by 0crat** [comment] 2018-07-21 09:43
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment] 2018-07-22 13:47
@amihaiemil the puzzle [#1466](https://github.com/zerocracy/farm/issues/1466) is still not solved.

**Closed** 2018-07-22 18:43 UTC
Labels: bug, scope

**Comment by 0crat** [comment] 2018-07-22 19:09
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2018-07-22 19:09
The job [#733](https://github.com/zerocracy/farm/issues/733) is now out of scope

**Comment by ypshenychka** [comment] 2018-07-22 19:41
@0crat quality good

**Comment by 0crat** [comment] 2018-07-22 19:52
Order was finished, quality is "good": +46 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment] 2018-07-22 19:52
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
