### ISSUE TITLE
0crat NumberFormatException on issue close

### ISSUE THREAD

**Issue by rgevaerd** [zerocracy/farm#1551] opened 2018-08-04 14:51 UTC
A 0crat unrecoverable error occurred here: https://github.com/zerocracy/farm/issues/721#issuecomment-410428205

I guess that due to that error, #721 is not continuing on 0crat workflow.

**Comment by 0crat** [comment] 2018-08-04 14:52
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment] 2018-08-04 15:05
@rgevaerd it's a duplicate of #1537

**Closed by g4s8** 2018-08-04 15:05 UTC
Labels: duplicate

**Comment by 0crat** [comment] 2018-08-04 15:26
Job `gh:zerocracy/farm#1551` is not assigned, can't get performer
