### ISSUE TITLE
Internal application error on /equity URL

### ISSUE THREAD

**Issue by scristalli** [zerocracy/farm#2077] opened 2019-06-13 10:10 UTC
Querying `https://www.0crat.com/equity/CJT4R32Q3` (project of which I am member, got there from link "proof" in the project page next to my equity), I get an error.
It doesn't seem temporary, reloading the page produces the same error again.
The only part that changes is the string after the `/download` URL, in the example below is `c7449d58-98d0-4a83-9bb7-7f8aa2e88a65` but it changes every time.

```
Internal application error

0.47.5, ${buildNumber}

Please, report it here. We will do our best to fix it as soon as possible. We're very sorry. 

java.lang.IllegalStateException: [GET https://www.0crat.com/equity/CJT4R32Q3] failed in 6s: HTTP response status is not equal to 200:
500 Internal Server Error [https://leta.infra.cloudconvert.com/download/c7449d58-98d0-4a83-9bb7-7f8aa2e88a65?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"2a-c5Yd735mWsST6SbM+ozpXm6eIAU"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 42
Date: Thu, 13 Jun 2019 09:50:18 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Converter not found","code":500}
Expected: HTTP response with status 200
     but: was <500 Internal Server Error [https://leta.infra.cloudconvert.com/download/c7449d58-98d0-4a83-9bb7-7f8aa2e88a65?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"2a-c5Yd735mWsST6SbM+ozpXm6eIAU"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 42
Date: Thu, 13 Jun 2019 09:50:18 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Converter not found","code":500}>
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: HTTP response status is not equal to 200:
500 Internal Server Error [https://leta.infra.cloudconvert.com/download/c7449d58-98d0-4a83-9bb7-7f8aa2e88a65?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"2a-c5Yd735mWsST6SbM+ozpXm6eIAU"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 42
Date: Thu, 13 Jun 2019 09:50:18 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Converter not found","code":500}
Expected: HTTP response with status 200
     but: was <500 Internal Server Error [https://leta.infra.cloudconvert.com/download/c7449d58-98d0-4a83-9bb7-7f8aa2e88a65?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"2a-c5Yd735mWsST6SbM+ozpXm6eIAU"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 42
Date: Thu, 13 Jun 2019 09:50:18 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Converter not found","code":500}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:111)
	at com.zerocracy.tools.Latex.pdf(Latex.java:103)
	at com.zerocracy.pm.cost.Equity.pdf(Equity.java:102)
	at com.zerocracy.tk.project.TkEquity.act(TkEquity.java:73)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:48)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
```

**Comment by 0crat** [comment] 2019-06-13 10:10
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-06-13 10:10
@scristalli[/z](https://www.0crat.com/u/scristalli) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by scristalli** [comment] 2019-06-20 16:15
@g4s8 can we confirm this issue? The problem persists, I get errors every time I try to access the equity URL from the "proof" link in the project page.

**Comment by g4s8** [comment] 2019-06-20 16:33
@scristalli thanks for reporting, it's a duplicate of #2073

**Closed by g4s8** 2019-06-20 16:33 UTC

**Comment by 0crat** [comment] 2019-06-20 16:34
Job `gh:zerocracy/farm#2077` is not assigned, can't get performer
