### ISSUE TITLE
Not getting points/payment for reporting a bug

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#983] opened 2018-05-02 15:05 UTC
I'm in cactoos project but recently when my bug report was accepted I didn't get any points/payment when I reported a [bug](https://github.com/yegor256/cactoos/issues/790).
Instead I saw two error [messages](https://github.com/yegor256/cactoos/issues/790#issuecomment-385965280):
```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-7
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

and 
```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-7
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: com.mongodb.MongoWriteException: quota exceeded
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

This shouldn't happen.

**Comment by 0crat** [comment] 2018-05-02 15:05
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-05-02 15:05
@krzyk[/z](https://www.0crat.com/u/krzyk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment] 2018-05-03 13:09
Job [#983](https://github.com/zerocracy/farm/issues/983) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-05-03 13:14
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment] 2018-06-12 14:20
The job [#983](https://github.com/zerocracy/farm/issues/983) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1631467066); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2018-06-17 14:36
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by proshin-roman** [comment] 2018-06-22 07:06
@0crat refuse

**Comment by 0crat** [comment] 2018-06-22 07:06
> @0crat refuse ([here](https://github.com/zerocracy/farm/issues/983#issuecomment-399343465))

@proshin-roman The user @proshin-roman[/z](https://www.0crat.com/u/proshin-roman) resigned from [#983](https://github.com/zerocracy/farm/issues/983), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-06-22 07:08
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment] 2018-06-22 10:29
The job [#983](https://github.com/zerocracy/farm/issues/983) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1731050739); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment] 2018-06-26 20:13
@krzyk Looks like MongoDb files reached their maximum number in database; https://docs.mongodb.com/manual/reference/configuration-options/#storage.mmapv1.quota.enforced we can see `quota` parameters. So I think we should tweak with these parameters a little, maybe add them up so our `MongoDB` instance will be able to handle more requests, WDYT?

**Comment by krzyk** [comment] 2018-06-26 20:47
@paulodamaso I think that's a good idea.

**Comment by 0crat** [comment] 2018-06-27 10:36
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment] 2018-06-27 13:48
@g4s8 Do we have any configuration file for `MongoDb` that is not in github? Are these quota settings already set anywhere or can I create a new mongo db configuration file for them?

**Comment by g4s8** [comment] 2018-06-27 14:11
@paulodamaso we have `<mongo>` section in `_props.xml`, BTW mongo is working now.

**Comment by paulodamaso** [comment] 2018-06-27 14:20
@g4s8 Sorry I've not expressed myself clearly: I need to know if we have these quota configurations already set in any file outside github, so I can define values for them based on the existing ones (if they exist). My fix here will be to set these configurations in a `mongobd` config file with these quota values and change mongodb calls in bash files to use this config file.

@g4s8 If you think that we do not need to tamper with mongodb configuration because `MongoDB` is working, just tell us so we can close this issue.

**Comment by g4s8** [comment] 2018-06-27 14:37
@paulodamaso I just don't understand how it will fix that. If mongo accepting new records now it means that we didn't exceed quota limits, right? But if we change the quota we have two possible scenarios:
 1. Nothing will happen, if quota value >= current value
 2. We will get quota error, if quota value < current value

Or maybe I'm missing something?

**Comment by paulodamaso** [comment] 2018-06-27 14:52
@g4s8 You are right, but I couldn't see another way of correcting this bug. Probably ZC was having a heavy demand at the time, but it is not having it now. I couldn't really tell you if it's what happened without having some reports or logs about that day (12th may I think), but we could take on that was a momentary one-time issue an let it be. So, if there's nothing to be done here (it was a one-time event due high demand), we should close this ticket.

**Comment by g4s8** [comment] 2018-06-27 15:09
@paulodamaso yes, maybe it depends on high-load. So let's increase quota limit, but please, make sure that it's greater than now.

**Comment by paulodamaso** [comment] 2018-06-27 15:23
@g4s8 All right, but is there any way of checking this value in current instance? `/etc/mongod.conf` could be setting it to some default value.

**Comment by g4s8** [comment] 2018-06-27 15:39
@paulodamaso there are no such file on instance

**Comment by paulodamaso** [comment] 2018-06-27 19:03
@g4s8 Digging deeper into `MongoDB` docs brought me that MongoDB uses two engines: `WiredTiger` (default from 3.2) or `MMAPv1` (default for versions prior 3.2). We only could set quota values in `MMAPv1` engine, so if we are using `WiredTiger` I think we have nothing else to do here. Which version are we using? Can we assume we are using `WiredTiger` because we are using version 3.5.0 of `MongoDB`?

**Comment by paulodamaso** [comment] 2018-06-29 12:31
@g4s8 So, what we do now? As the problem is related to heavy loading, I suggest we just close this issue since it's not happening anymore. WDYT?

**Comment by g4s8** [comment] 2018-06-29 13:03
@paulodamaso yes, looks like it was temporary issue, becuase I can't find fresh exceptions like this one in Sentry. @krzyk what do you think?

**Comment by krzyk** [comment] 2018-06-29 13:23
@g4s8 yes, i think so too. Never seen more of it.

**Comment by paulodamaso** [comment] 2018-06-29 14:15
@krzyk @g4s8 So we're done here, thanks for the patience.

**Comment by paulodamaso** [comment] 2018-06-29 14:15
@krzyk close please

**Closed** 2018-06-29 14:21 UTC
Labels: bug, scope

**Comment by 0crat** [comment] 2018-06-29 14:36
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2018-06-29 14:37
The job [#983](https://github.com/zerocracy/farm/issues/983) is now out of scope

**Comment by ypshenychka** [comment] 2018-06-29 15:42
@g4s8 Please advise about quality here. Is it "bad" since no solution was provided (or a unit test for example), or "acceptable" since performer still spent some time in digging into this?

**Comment by paulodamaso** [comment] 2018-06-30 18:50
@g4s8 Ping

**Comment by g4s8** [comment] 2018-07-01 09:57
@ypshenychka @paulodamaso I think quality of this job is bad, because this discussion didn't produce any conclusion, such as documentation changes or new pdd-puzzle or unit test.

**Comment by ypshenychka** [comment] 2018-07-01 10:19
@g4s8 Thank you.

**Comment by ypshenychka** [comment] 2018-07-01 10:20
@0crat quality bad

**Comment by 0crat** [comment] 2018-07-01 10:22
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment] 2018-07-01 10:22
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by g4s8** [comment] 2018-07-02 08:22
@paulodamaso research results have to be documented somewhere to not lose them. If this bug reproduced again, the performer most probably will do same research to find the reason, I mean, that your research will not help to fix same issue in the future.
