### ISSUE TITLE
I've got my own PR for review

### ISSUE THREAD

**Issue by olenagerasimova** [zerocracy/farm#2115] opened 2019-07-13 16:09 UTC
0crat just asked me to review my own pull request. Check details in https://github.com/g4s8/ghman/pull/64, everything else is as usual: I've message in telegram and the job is in my agenda

**Comment by 0crat** [comment] 2019-07-13 16:09
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-07-13 16:09
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment] 2019-07-14 06:47
@olenagerasimova thanks for reporting, but it's a duplicate of #1787
will try to fix it soon

**Closed by g4s8** 2019-07-14 06:47 UTC
Labels: duplicate

**Comment by 0crat** [comment] 2019-07-14 06:49
Job `gh:zerocracy/farm#2115` is not assigned, can't get performer
