### ISSUE TITLE
Allow someone who was kicked out sandbox project for reached more than 1024 points, return if he/she want to

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/farm#1882] opened 2019-02-02 16:24 UTC
@yegor256 @g4s8 Let's allow someone who was kicked out sandbox project for reached more than 1024 points, return if he/she want to. WDYT?

**Comment by fabriciofx** [comment] 2019-02-02 23:40
@yegor256 @g4s8 A suggestion: the *veteran* who choose return to a sandbox will work for free, but will just receive points.

**Comment by g4s8** [comment] 2019-05-28 08:06
@fabriciofx it's a duplicate of #2030

**Closed by g4s8** 2019-05-28 08:06 UTC

**Comment by 0crat** [comment] 2019-05-28 08:24
Job `gh:zerocracy/farm#1882` is not assigned, can't get performer

**Comment by 0crat** [comment] 2019-05-28 08:24
This job is not in scope
