### ISSUE TITLE
Add a docker environment

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/farm#1834] opened 2018-12-27 03:01 UTC
Let's add a docker environment to allow any dev to build/run/test `farm` before submit any PR.

**Comment by 0crat** [comment] 2018-12-27 03:02
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-12-27 03:02
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment] 2018-12-27 09:07
@fabriciofx you can run tests with maven using `mvn install`, you don't need docker for that. Docker may help only to run farm, but actually you don't need it, see https://www.yegor256.com/2016/02/09/are-you-still-debugging.html
BTW Docker will not help here, there are a lot of AWS services you will need to setup and pay to be able to run farm.
Duplicate of #1712

**Closed by g4s8** 2018-12-27 09:07 UTC
