### ISSUE TITLE
Equity proof page error

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#996] opened 2018-05-04 15:32 UTC
When I go to https://www.0crat.com/equity/C3NDPUA8L I'm presented with an error page:
```
java.lang.IllegalStateException: [GET https://www.0crat.com/equity/C3NDPUA8L] failed in 4s: HTTP response status is not equal to 200:
422 Unprocessable Entity [https://hostq81gk9.cloudconvert.com/download/3bersavu2I7QljR1gDi9?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"44-DM9oKUrbqU6X/bfOf8G1tHs4zwA"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 68
Date: Fri, 04 May 2018 15:30:35 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Transcript written on /data//article.log.\r\n","code":422}
Expected: HTTP response with status 200
     but: was <422 Unprocessable Entity [https://hostq81gk9.cloudconvert.com/download/3bersavu2I7QljR1gDi9?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"44-DM9oKUrbqU6X/bfOf8G1tHs4zwA"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 68
Date: Fri, 04 May 2018 15:30:35 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Transcript written on /data//article.log.\r\n","code":422}>
	at org.takes.facets.fallback.TkFallback.error(TkFallback.java:234)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:115)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkSslOnly.act(TkSslOnly.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:108)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
	at org.takes.http.BkWrap.accept(BkWrap.java:52)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:89)
	at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: HTTP response status is not equal to 200:
422 Unprocessable Entity [https://hostq81gk9.cloudconvert.com/download/3bersavu2I7QljR1gDi9?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"44-DM9oKUrbqU6X/bfOf8G1tHs4zwA"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 68
Date: Fri, 04 May 2018 15:30:35 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Transcript written on /data//article.log.\r\n","code":422}
Expected: HTTP response with status 200
     but: was <422 Unprocessable Entity [https://hostq81gk9.cloudconvert.com/download/3bersavu2I7QljR1gDi9?inline]
Cache-Control: no-cache, no-store, must-revalidate
ETag: W/"44-DM9oKUrbqU6X/bfOf8G1tHs4zwA"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS, GET, PUT, POST, DELETE
Connection: keep-alive
Expires: 0
Pragma: no-cache
Content-Length: 68
Date: Fri, 04 May 2018 15:30:35 GMT
Access-Control-Allow-Headers: Content-Type, Origin, User-Agent, Retry-After
Content-Type: application/json; charset=utf-8

{"error":"Transcript written on /data//article.log.\r\n","code":422}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:111)
	at com.zerocracy.tools.Latex.pdf(Latex.java:105)
	at com.zerocracy.pm.cost.Equity.pdf(Equity.java:104)
	at com.zerocracy.tk.project.TkEquity.act(TkEquity.java:75)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:210)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at com.zerocracy.tk.TkSoftForward.lambda$new$0(TkSoftForward.java:50)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fork.FkFixed$1.route(FkFixed.java:56)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.FkChain.route(FkChain.java:75)
	at org.takes.facets.fork.TkFork.act(TkFork.java:100)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:108)
	at org.takes.tk.TkGzip$1.act(TkGzip.java:58)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:73)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:86)
	... 14 more
```

I would expect not to see the error, but the actual page :)

**Comment by 0crat** [comment] 2018-05-04 15:32
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by g4s8** [comment] 2019-06-08 14:41
@krzyk thanks for reporting but it's a duplicate of #852

**Closed by g4s8** 2019-06-08 14:41 UTC

**Comment by 0crat** [comment] 2019-06-08 14:57
Job `gh:zerocracy/farm#996` is not assigned, can't get performer

**Comment by 0crat** [comment] 2019-06-08 14:58
This job is not in scope
