### ISSUE TITLE
Agenda "Added" Column Seems Broken

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#1301] opened 2018-07-01 18:06 UTC
Maybe it was a temporary issue (since the latest job's addition time is correct), but some jobs in my agenda have negative addition times, in minutes:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/6305156/42137301-a6344a24-7d72-11e8-99ea-2355f0c02396.png">

**Comment by 0crat** [comment] 2018-07-01 18:06
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment] 2018-07-01 21:08
@amihaiemil it's a duplicate of https://github.com/zerocracy/datum/issues/362, looks like xsl was broken with recent changes related to time formatting

**Closed by g4s8** 2018-07-01 21:08 UTC
