### ISSUE TITLE
remove_old_vacancies.groovy:36-39: Notify all project...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1257] opened 2018-06-26 17:15 UTC
The puzzle `917-ba7a1a04` from #917 has to be resolved:

https://github.com/zerocracy/farm/blob/6548895bed74f7a92acaa0e6bbfd7f5d87b3c689/src/main/groovy/com/zerocracy/stk/pmo/vacancies/remove_old_vacancies.groovy#L36-L39

The puzzle was created by g4s8 on 26-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment] 2018-06-26 17:16
Job [#1257](https://github.com/zerocracy/farm/issues/1257) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-06-26 17:16
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-07-30 17:23
The job [#1257](https://github.com/zerocracy/farm/issues/1257) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2111729645); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment] 2018-08-03 15:33
The puzzle `917-ba7a1a04` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment] 2018-08-03 15:34
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@7bda313d-71fb-41d0-8d6f-eda5801ea74b, thread: pool-203-thread-1
java.lang.NumberFormatException[65] java.lang.NumberFormatException: For input string: "2018-08-03T15:49:11.139Z"
```

[0.28.15](https://github.com/zerocracy/farm): Issue: zerocracy/farm#1257, Action: `closed`

**Comment by 0pdd** [comment] 2018-08-03 15:34
@0pdd the puzzle [#1543](https://github.com/zerocracy/farm/issues/1543) is still not solved.

**Comment by 0crat** [comment] 2018-08-04 18:53
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment] 2018-08-04 20:52
@0crat out

**Comment by 0crat** [comment] 2018-08-04 21:03
@krzyk[/z](https://www.0crat.com/u/krzyk) the issue is closed not by @0pdd[/z](https://www.0crat.com/u/0pdd) (its creator); I won't close the order; please, re-open it and ask @0pdd[/z](https://www.0crat.com/u/0pdd) to close it

**Comment by krzyk** [comment] 2018-08-04 21:04
@g4s8 problem here with moving to QA, 0crat doesn't recognize that 0pdd closed the job (I think all 0pdd closed jobs during the transition to SQS will be affected, this is the second time I see it after `out`)

**Comment by krzyk** [comment] 2018-08-06 09:28
@0crat out

**Comment by 0crat** [comment] 2018-08-06 09:29
> @0crat out ([here](https://github.com/zerocracy/farm/issues/1257#issuecomment-410646678))

@krzyk There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ac39efbd-44bb-4133-afd1-d4f87fda007d, thread: AsyncProc-4
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zerocracy/farm#1257] declared for identity constraint of element "verbosity".
```

[0.29.6](https://github.com/zerocracy/farm): CID: [2180937005](https://www.0crat.com/C3NDPUA8L/2180937005), Type: "Close job", Author: "krzyk"

**Comment by 0crat** [comment] 2018-08-06 09:29
@krzyk[/z](https://www.0crat.com/u/krzyk) the issue is closed not by @0pdd[/z](https://www.0crat.com/u/0pdd) (its creator); I won't close the order; please, re-open it and ask @0pdd[/z](https://www.0crat.com/u/0pdd) to close it

**Comment by 0crat** [comment] 2018-08-06 09:44
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Closed by 0crat** 2018-08-06 09:44 UTC
Labels: bug, pdd, scope

**Comment by 0crat** [comment] 2018-08-06 10:01
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ac39efbd-44bb-4133-afd1-d4f87fda007d, thread: AsyncProc-8
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zerocracy/farm#1257] declared for identity constraint of element "verbosity".
```

[0.29.6](https://github.com/zerocracy/farm): CID: [2180953491](https://www.0crat.com/C3NDPUA8L/2180953491), Type: "Close job", Author: "g4s8"

**Comment by 0crat** [comment] 2018-08-06 10:02
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2018-08-06 10:03
The job [#1257](https://github.com/zerocracy/farm/issues/1257) is now out of scope

**Comment by ypshenychka** [comment] 2018-08-06 10:47
@0crat quality good

**Comment by 0crat** [comment] 2018-08-06 10:52
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment] 2018-08-06 10:52
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment] 2022-07-15 21:06
@0pdd the puzzle [#unknown]() is still not solved.
