### ISSUE TITLE
Adding job to a milestone gives an error

### ISSUE THREAD

**Issue by ammaratef45** [zerocracy/farm#2074] opened 2019-06-09 12:36 UTC
In ammaratef45/zold-flutter-client#118, When I've added the job to a milestone I got the following from zercrat
> There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):
> 
> ```
> PID: 4@c6675062-cc84-4507-ab95-22913e5b7093, thread: pool-19-thread-7
> com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'gh:V 1.3' is not facet-valid with respect to pattern '[a-z]{2}:[A-Z0-9a-z.\-#/]+' for type 'milestoneID'.;-1:-1: cvc-complex-type.2.2: Element 'successor' must have no element [children], and the value must be valid.
> ```
> 
> [0.47.5](https://github.com/zerocracy/farm): CID: [d448c958-1167-4723-b057-0181a04e1a86](https://www.0crat.com/footprint/CGC59KB9B/d448c958-1167-4723-b057-0181a04e1a86), Type: "Job milestoned"

**Comment by 0crat** [comment] 2019-06-09 12:36
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-06-09 12:36
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment] 2019-06-11 07:03
@ammaratef45 thanks for reporting, but it's a duplicate of #2051, will try to fix it soon

**Closed by g4s8** 2019-06-11 07:03 UTC
Labels: duplicate

**Comment by ammaratef45** [comment] 2019-06-11 07:07
@g4s8 A lot of duplicates :laughing: 

Good luck :+1:

**Comment by 0crat** [comment] 2019-06-11 07:11
Job `gh:zerocracy/farm#2074` is not assigned, can't get performer
