### ISSUE TITLE
0crat assigned REV job to DEV

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/farm#1830] opened 2018-12-18 21:00 UTC
Happened with me on https://github.com/jcabi/jcabi-github/issues/1454 :
I've made the PR, my role was `DEV`, but `0crat` insisted and assigned me as `REV` on this one too
So both of issues are on my agenda:
![image](https://user-images.githubusercontent.com/33915433/50182635-0379c380-02f7-11e9-80e2-dacb049d03d8.png)

![image](https://user-images.githubusercontent.com/33915433/50182672-1be9de00-02f7-11e9-8885-7ea08ea039ac.png)

**Comment by 0crat** [comment] 2018-12-18 21:00
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by paulodamaso** [comment] 2018-12-27 15:40
@g4s8 happened again in https://github.com/amihaiemil/docker-java-api/pull/247 : 0crat assigned me my own PR. The foorprint: https://www.0crat.com/footprint/G6LPQQV2P/881a8aa9-e31a-4eda-ba7e-492040818186

**Comment by fabriciofx** [comment] 2019-01-04 02:21
@g4s8 Its happening with me too. I'm as DEV in Cactoos but I've been received jobs as REV.

**Comment by g4s8** [comment] 2019-01-16 06:18
@paulodamaso @fabriciofx will try to solve it soon

**Comment by g4s8** [comment] 2019-01-16 06:19
Duplicate of #1787

**Closed** 2019-01-16 06:19 UTC

**Comment by 0crat** [comment] 2019-01-16 06:40
Job `gh:zerocracy/farm#1830` is not assigned, can't get performer

**Comment by 0crat** [comment] 2019-01-16 06:43
This job is not in scope
