### ISSUE TITLE
0crat assigned me a PR as REV that I had submitted

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1965] opened 2019-03-29 11:11 UTC
See https://github.com/yegor256/cactoos/pull/1087

I would expect not to be assigned such PR :)

**Comment by 0crat** [comment] 2019-03-29 11:11
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment] 2019-03-31 19:09
@g4s8 it happened again: https://github.com/yegor256/cactoos/pull/1092

**Comment by g4s8** [comment] 2019-04-01 08:27
@victornoel thanks, but it's a duplicate of #1787

**Comment by 0crat** [comment] 2019-04-01 08:28
Job `gh:zerocracy/farm#1965` is not assigned, can't get performer

**Closed by g4s8** 2019-04-01 08:27 UTC
Labels: duplicate
