### ISSUE TITLE
Unrecoverable issue after QA review #585

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#614] opened 2018-02-20 19:07 UTC
https://github.com/yegor256/cactoos/issues/585#issuecomment-367076457
>@ypshenychka There is an unrecoverable failure on my side. Please, submit it here:

>com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.GeneratedMethodAccessor61[-1] java.lang.reflect.InvocationTargetException: null
com.zerocracy.pmo.banks.Paypal[122] java.io.IOException: Failed to pay $8.00 to driver733@me.com with memo "Payment for gh:yegor256/cactoos#585 (30 minutes): Order was finished, quality was "acceptable"": java.io.IOException Failed to pay through PayPal: [ERROR APPLICATION The payment can not be processed because no payment source is available]
com.zerocracy.pmo.banks.Paypal[202] java.io.IOException: Failed to pay through PayPal: [ERROR APPLICATION The payment can not be processed because no payment source is available]

**Comment by 0crat** [comment] 2018-02-20 19:07
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment] 2018-02-20 19:22
@ypshenychka duplicate of #606

**Closed by yegor256** 2018-02-20 19:22 UTC
