### ISSUE TITLE
0crat assigned closed job again

### ISSUE THREAD

**Issue by rexim** [zerocracy/farm#588] opened 2018-02-17 20:32 UTC
As per https://github.com/zerocracy/farm/issues/571#issuecomment-366269644 I'm filing another issue. See https://github.com/yegor256/cactoos/issues/629#issuecomment-366422935

**Comment by 0crat** [comment] 2018-02-17 20:32
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment] 2018-02-19 13:24
@rexim it's by design, the ticket was still in scope. Fixed in the ticket.

**Closed by yegor256** 2018-02-19 13:24 UTC
