### ISSUE TITLE
CR is sometimes useless

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#623] opened 2018-02-22 08:46 UTC
In the past, with Teamed, the PMs would assign a Pull Request directly to the ARCH if it was very small. 

I think this mechanism is needed for 0crat as well, since there are some very small PRs around (modifying README, modifying some puzzles etc) -- it's a waste of time and money to assign CR/ARCH/QA for such small PRs. Besides, the QA will always complain in these cases since it's not possible to find 3 problems in such PRs, as the Policy requires.

**Comment by 0crat** [comment] 2018-02-22 08:46
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment] 2018-02-22 15:19
@amihaiemil duplicate of #510

**Closed by yegor256** 2018-02-22 15:19 UTC
