### ISSUE TITLE
0crat awaiting QA verdict, but did not inform QA performer

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/farm#803] opened 2018-03-13 08:22 UTC
In #786 the PR was merged successfully. No further messages were recorded from `@0crat`. When I asked for status, it says it's in QA review, but it did not inform the QA performer.

![image](https://user-images.githubusercontent.com/1917892/37329951-7592689a-26da-11e8-8cf4-a43e20e156c6.png)

**Comment by amihaiemil** [comment] 2018-03-13 09:16
@carlosmiranda I am not sure but I think this Issue is already raised. There was an issue about "0crat silently assigns performer" -- it seems to be the same bug. But let's see...

**Comment by 0crat** [comment] 2018-03-13 10:23
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment] 2018-03-13 12:01
@carlosmiranda the problem is that GitHub sometimes blocks us, especially when we ping their API too frequently.

**Comment by yegor256** [comment] 2018-03-13 12:02
@carlosmiranda I'll close this as dup of #564

**Closed by yegor256** 2018-03-13 12:02 UTC
