### ISSUE TITLE
0crat assigns REV job to the same DEV who created PR

### ISSUE THREAD

**Issue by ilyakharlamov** [zerocracy/farm#2031] opened 2019-05-08 22:13 UTC
Steps to reproduce:

1. Create a project with few dev/rev, for example just one or two.
2. Create A PR as DEV

What's wrong:
0crat can assign the REV job to the same developer who submitted the PR.

Might also be related: #1830

Reproduced on version v0.46.9

**Comment by 0crat** [comment] 2019-05-08 22:13
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-05-08 22:13
@ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment] 2019-05-09 07:47
@ilyakharlamov thanks for reporting, but it's a duplicate of #1787

**Closed by g4s8** 2019-05-09 07:47 UTC

**Comment by 0crat** [comment] 2019-05-09 07:50
Job `gh:zerocracy/farm#2031` is not assigned, can't get performer
