### ISSUE TITLE
0crat didn't pay for QA review without any notification about failure

### ISSUE THREAD

**Issue by elenavolokhova** [zerocracy/farm#1005] opened 2018-05-10 22:15 UTC
Happened in [#830](https://github.com/yegor256/cactoos/pull/830)
Points for QA were not rewarded.

**Comment by 0crat** [comment] 2018-05-10 22:15
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-05-10 22:15
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by elenavolokhova** [comment] 2018-05-19 21:52
@yegor256 Happened in [#863](https://github.com/yegor256/cactoos/pull/863) too.

**Comment by yegor256** [comment] 2018-05-21 16:49
@elenavolokhova seems to be a duplicate of #1004 Won't happen again, I believe.

**Closed by yegor256** 2018-05-21 16:49 UTC

**Comment by 0crat** [comment] 2018-05-21 17:04
The job is not in WBS, won't close the order
