### ISSUE TITLE
Failure when inviting someone in Telegram

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#1322] opened 2018-07-03 07:49 UTC
After application from new user, I've invited him in Telegram through 0crat bot. Error is copied below. But in fact user is invited.

>There is an unrecoverable failure on my side. Please, submit it here (https://github.com/zerocracy/farm/issues):

>PID: 4@cb3e614a-112c-4fc3-b9f6-78a7ca388929, thread: AsyncFlush-2
org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl[252] java.lang.ClassCastException: javax.json.JsonValueImpl cannot be cast to javax.json.JsonString

>0.24.5 (https://github.com/zerocracy/farm): CID: 1840749104 (https://www.0crat.com/PMO/1840749104), Type: "Invite a friend", Author: "ypshenychka"

>zerocracy/farm
>farm - Zerocrat Core Engine

**Comment by 0crat** [comment] 2018-07-03 07:49
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by amihaiemil** [comment] 2018-07-03 07:56
@ypshenychka Is that the whole stacktrace of the exception? This is a very trivial error and it should tell you exactly at which line, in which file, the error occured :)

**Comment by ypshenychka** [comment] 2018-07-03 08:09
@amihaiemil That's what I see in chat. Please tell me where can I see whole stacktrace.
![image](https://user-images.githubusercontent.com/11703257/42207017-7c945cc8-7eb1-11e8-99de-0a2c9243d45c.png)

**Comment by amihaiemil** [comment] 2018-07-03 08:10
@ypshenychka I see. Then the whole stacktrace should be in the logs. I thought maybe it gave you more information (on Github, for instance, it writes the whole stacktrace usually)

**Comment by ypshenychka** [comment] 2018-07-03 08:12
@amihaiemil Thanks. Yesterady I had exactly the same error. So it's actually started yesterday.
![image](https://user-images.githubusercontent.com/11703257/42207167-ec1a8798-7eb1-11e8-8af0-1e7e3427fbed.png)

**Comment by g4s8** [comment] 2018-07-03 11:59
@ypshenychka thanks, but it's a duplicate of #1166

**Closed by g4s8** 2018-07-03 11:59 UTC
Labels: duplicate

**Comment by 0crat** [comment] 2018-07-03 12:05
Job `gh:zerocracy/farm#1322` is not assigned, can't get performer
